.gitignore

Signed-off-by: Andrei Gherzan <andrei@resin.io>

.gitignore: Ignore log files

---

recipes-graphics/userland/userland_git.bb

userland: Update to latest

---

recipes-graphics/userland/userland_git.bb
recipes-kernel/linux/linux-raspberrypi_4.9.bb

I'm trying this out as a pull request as it should get Jenkins to run a build...

Update pyro with latest changes on master

---

conf/machine/raspberrypi3-64.conf

This causes problems and raspberrypi3 does not do that.
connect https://github.com/agherzan/meta-raspberrypi/issues/85

raspberrypi3-64 shouldn't inherit raspberrypi.

---

recipes-kernel/linux/linux-raspberrypi_4.9.bb

Boot tested on raspberrypi & raspberrypi3.

linux-rasbperrypi: Update to 4.9.35

---

classes/sdcard_image-rpi.bbclass
conf/machine/raspberrypi3-64.conf
recipes-devtools/pi-blaster/files/remove-initscript-lsb-dependency.patch
recipes-devtools/pi-blaster/pi-blaster.inc
recipes-devtools/pi-blaster/pi-blaster_git.bb
recipes-kernel/linux/linux-raspberrypi-dev.bb

This is the last simple merge of master -> pyro as commit fc17cd74191e248386d4874a5a7afc1de49e9922 is not wanted on pyro. After this we'll cherry-pick commits as needed.

[pyro] Update with changes from master

---

recipes-bsp/u-boot/u-boot/0001-Revert-dm-arm-rpi-Drop-CONFIG_OF_EMBED.patch
recipes-bsp/u-boot/u-boot/0002-rpi-Enable-USB-keyboard-support.patch
recipes-bsp/u-boot/u-boot_%.bbappend

u-boot: Fix boot and keyboard for rpi devices

---

recipes-kernel/linux/linux-raspberrypi.inc
recipes-kernel/linux/linux-raspberrypi/defconfig
recipes-kernel/linux/linux-rpi.inc

This patch fixes issues #14 and replace previous PR
I have updated the patch available in the mailing list and with this patch is possible to extend the kernel configuration via bbappend and cfg fragments.

Fix issue 14 - extend kernel configuration

---

recipes-bsp/common/firmware.inc
recipes-devtools/python/rpio_0.10.0.bb
recipes-kernel/linux/linux-raspberrypi_4.9.bb

Backport the following from master:
* linux-raspberrypi updates
* firmware updates
* rpio runtime dependency fix

Backports for pyro

---

recipes-connectivity/bluez5/bluez5_%.bbappend

Enabled bluetooth on raspberrypi0-wifi.
Added functions/variables to simplify to enabling bluetooth on another raspberrypi that has bluetooth.

bluez5: add functions for raspberrypi0-wifi

---

README

Found #78 that has been open for a while.
Might as well fix and close it.

README: update dependencies

---

conf/machine/raspberrypi3-64.conf
recipes-bsp/bootfiles/rpi-config_git.bb
recipes-graphics/xorg-xserver/xserver-xf86-config/rpi/xorg.conf.d/10-noglamor.conf
recipes-graphics/xorg-xserver/xserver-xf86-config_0.1.bbappend
recipes-kernel/linux/linux-raspberrypi.inc
recipes-kernel/linux/linux-raspberrypi_4.9.bb

Fix graphics on raspberrypi3-64

---

recipes-connectivity/bluez5/bluez5_%.bbappend
recipes-kernel/linux-firmware/linux-firmware_%.bbappend
recipes-kernel/linux/linux-raspberrypi.inc

 Replace /lib with ${nonarch_base_libdir}

---

recipes-graphics/userland/userland/0001-Allow-applications-to-set-next-resource-handle.patch
recipes-graphics/userland/userland/0002-wayland-Add-support-for-the-Wayland-winsys.patch
recipes-graphics/userland/userland/0003-wayland-Add-Wayland-example.patch
recipes-graphics/userland/userland/0004-wayland-egl-Add-bcm_host-to-dependencies.patch
recipes-graphics/userland/userland/0005-interface-remove-faulty-assert-to-make-weston-happy-.patch
recipes-graphics/userland/userland/0006-zero-out-wl-buffers-in-egl_surface_free.patch
recipes-graphics/userland/userland/0007-initialize-front-back-wayland-buffers.patch
recipes-graphics/userland/userland/0008-Remove-RPC_FLUSH.patch
recipes-graphics/userland/userland/0009-fix-cmake-dependency-race.patch
recipes-graphics/userland/userland/0010-Fix-for-framerate-with-nested-composition.patch
recipes-graphics/userland/userland/0011-build-shared-library-for-vchostif.patch
recipes-graphics/userland/userland/0012-implement-buffer-wrapping-interface-for-dispmanx.patch
recipes-graphics/userland/userland/0013-Implement-triple-buffering-for-wayland.patch
recipes-graphics/userland/userland/0014-GLES2-gl2ext.h-Define-GL_R8_EXT-and-GL_RG8_EXT.patch
recipes-graphics/userland/userland/0015-EGL-glplatform.h-define-EGL_CAST.patch
recipes-graphics/userland/userland_git.bb

Forward port patches as needed

userland: Update to latest revision

---

conf/machine/raspberrypi0-wifi.conf
conf/machine/raspberrypi3.conf

Small cleanup of KERNEL_DEFCONFIG.

Small cleanup of KERNEL_DEFCONFIG

---

recipes-graphics/userland/userland_git.bb
recipes-multimedia/x264/x264_git.bbappend

Two backports from master for the rocko branch to fix issues I ran into.

Rocko backports

---

conf/machine/include/rpi-base.inc
recipes-connectivity/bluez5/bluez5/brcm43438.service
recipes-connectivity/bluez5/bluez5_%.bbappend

Switch from hardcoded device node to serial1 using the udev rules.

Use serial1 for bluetooth

---

recipes-kernel/linux/linux-raspberrypi.inc

recipes: use oe.utils.conditional instead of deprecated base_conditional

---

recipes-graphics/userland/userland/0001-Allow-applications-to-set-next-resource-handle.patch
recipes-graphics/userland/userland/0002-wayland-Add-support-for-the-Wayland-winsys.patch
recipes-graphics/userland/userland/0003-wayland-Add-Wayland-example.patch
recipes-graphics/userland/userland/0004-wayland-egl-Add-bcm_host-to-dependencies.patch
recipes-graphics/userland/userland/0005-interface-remove-faulty-assert-to-make-weston-happy-.patch
recipes-graphics/userland/userland/0006-zero-out-wl-buffers-in-egl_surface_free.patch
recipes-graphics/userland/userland/0007-initialize-front-back-wayland-buffers.patch
recipes-graphics/userland/userland/0008-Remove-RPC_FLUSH.patch
recipes-graphics/userland/userland/0009-fix-cmake-dependency-race.patch
recipes-graphics/userland/userland/0010-Fix-for-framerate-with-nested-composition.patch
recipes-graphics/userland/userland/0011-build-shared-library-for-vchostif.patch
recipes-graphics/userland/userland/0012-implement-buffer-wrapping-interface-for-dispmanx.patch
recipes-graphics/userland/userland/0013-Implement-triple-buffering-for-wayland.patch
recipes-graphics/userland/userland/0014-GLES2-gl2ext.h-Define-GL_R8_EXT-and-GL_RG8_EXT.patch
recipes-graphics/userland/userland/0015-EGL-glplatform.h-define-EGL_CAST.patch
recipes-graphics/userland/userland/0016-Allow-multiple-wayland-compositor-state-data-per-pro.patch
recipes-graphics/userland/userland_git.bb

Update userland to latest

---

recipes-bsp/common/firmware.inc
recipes-graphics/userland/userland/0002-wayland-Add-support-for-the-Wayland-winsys.patch
recipes-graphics/userland/userland_git.bb
recipes-kernel/linux/linux-raspberrypi_4.14.bb

Firmware and userland updates are needed for 4.14 to work.

Upgrade to 4.14 kernel

---

recipes-core/udev/udev-rules-udisks-rpi/80-udisks-rpi.rules
recipes-core/udev/udev-rules-udisks-rpi_1.0.bb
recipes-graphics/mesa/mesa_%.bbappend

1. Enable dri3 whatever oe-core decides
2. Hide first boot partitions from Desktops using udisks

Very first merge back commits from meta-raspi-light

---

recipes-graphics/xorg-xserver/xserver-xf86-config_0.1.bbappend
recipes-kernel/linux/linux-raspberrypi.inc
recipes-sato/webkitgtk/webkitgtk_%.bbappend

These are misc changes needed for vc4graphics to work.

Fix X11 runtime with vc4graphics, disable kernel console along when ENABLE_UART is unset

---

recipes-bsp/bootfiles/rpi-config_git.bb

Signed-off-by: Eduardo Abinader <eduardoabinader@gmail.com>

config_git.bb: Remove extra space

---

conf/machine/raspberrypi3-64.conf
recipes-bsp/bootfiles/rpi-config_git.bb

Forward port from #255.  Not tested by me.

raspberrypi3-64.conf: add MACHINE override and 3B+ device tree

---

recipes-multimedia/omxplayer/omxplayer/0001-Remove-Makefile.include-which-includes-hardcoded.patch
recipes-multimedia/omxplayer/omxplayer/0002-Libraries-and-headers-from-ffmpeg-are-installed-in-u.patch
recipes-multimedia/omxplayer/omxplayer/0003-Remove-strip-step-in-Makefile.patch
recipes-multimedia/omxplayer/omxplayer/0004-Add-FFMPEG_EXTRA_CFLAGS-and-FFMPEG_EXTRA_LDFLAGS.patch
recipes-multimedia/omxplayer/omxplayer/0005-Don-t-require-internet-connection-during-build.patch
recipes-multimedia/omxplayer/omxplayer/0006-Prevent-ffmpeg-configure-compile-race-condition.patch
recipes-multimedia/omxplayer/omxplayer/fix-tar-command-with-DIST.patch
recipes-multimedia/omxplayer/omxplayer/use-native-pkg-config.patch

omxplayer: refresh and clean-up patches

---

recipes-kernel/linux-firmware/linux-firmware_%.bbappend

linux-firmware: update Cypress license checksum

---

recipes-graphics/wayland/weston_%.bbappend
recipes-kernel/linux/linux-raspberrypi_4.9.bb

First commit fixes the OOM errors.
Second commit fixes Linux kernel warning "unbalanced IRQ enable" when using vc4
Fixes #286

Rocko fix wayland together with vc4

---

conf/machine/include/rpi-base.inc
conf/machine/raspberrypi3-64.conf
recipes-kernel/linux/linux-raspberrypi_4.14.bb

Restructured the dtb variables and fix kernel build for raspberrypi3-64. Included an update as well.

Fix kernel for 64bit machine

---

recipes-kernel/linux-firmware/linux-firmware_%.bbappend

The same as corresponding changes for master from:
https://github.com/agherzan/meta-raspberrypi/pull/295
https://github.com/agherzan/meta-raspberrypi/pull/296
needed for latest oe-core/sumo revision with:
http://git.openembedded.org/openembedded-core/commit/?h=sumo&id=27fc32b6c5231b3539940d1e260ab1df3ea4bd14
http://git.openembedded.org/openembedded-core/commit/?h=sumo&id=75caa5dfc79df02b12f1b077ccbd80e4d69c9ead
http://git.openembedded.org/openembedded-core/commit/?h=sumo&id=75caa5dfc79df02b12f1b077ccbd80e4d69c9ead

linux-firmware fix for latest sumo revision

---

recipes-core/images/rpi-hwup-image.bb

…ge rpi-hwup-image, to recommend using core-image-base.

Modify warning message for deprecated rpi-hwup-target

---

docs/extra-build-config.md
recipes-multimedia/omxplayer/omxplayer/0001-Fix-build-with-vc4-driver.patch
recipes-multimedia/omxplayer/omxplayer_git.bb

omxplayer: Fix build when using vc4graphics driver

---

docs/extra-build-config.md

docs: Add more info on generating initramfs images

---

recipes-kernel/linux/linux-raspberrypi_4.14.bb

Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

linux-raspberrypi: Update to 4.14.85

---

conf/layer.conf

layer.conf: Fix typo for openembedded-layer dynamic layer addition

---

recipes-bsp/common/firmware.inc
recipes-kernel/linux/linux-raspberrypi_4.14.bb

Updated RaspberryPi kernel and firmware.

linux-raspberrypi: Update to 4.14.98

---

conf/machine/raspberrypi-cm3.conf
docs/layer-contents.md

Make the cm3 machine stand alone and test core image basic with cm3 and cm3+ in both with uboot and without configurations

CM3 improvements and tests

---

conf/machine/include/rpi-base.inc
conf/machine/include/rpi-default-versions.inc
recipes-bsp/common/firmware.inc
recipes-graphics/userland/files/0001-Allow-applications-to-set-next-resource-handle.patch
recipes-graphics/userland/files/0002-wayland-Add-support-for-the-Wayland-winsys.patch
recipes-graphics/userland/files/0003-wayland-Add-Wayland-example.patch
recipes-graphics/userland/files/0004-wayland-egl-Add-bcm_host-to-dependencies.patch
recipes-graphics/userland/files/0005-interface-remove-faulty-assert-to-make-weston-happy-.patch
recipes-graphics/userland/files/0006-zero-out-wl-buffers-in-egl_surface_free.patch
recipes-graphics/userland/files/0007-initialize-front-back-wayland-buffers.patch
recipes-graphics/userland/files/0008-Remove-RPC_FLUSH.patch
recipes-graphics/userland/files/0009-fix-cmake-dependency-race.patch
recipes-graphics/userland/files/0010-Fix-for-framerate-with-nested-composition.patch
recipes-graphics/userland/files/0011-build-shared-library-for-vchostif.patch
recipes-graphics/userland/files/0012-implement-buffer-wrapping-interface-for-dispmanx.patch
recipes-graphics/userland/files/0013-Implement-triple-buffering-for-wayland.patch
recipes-graphics/userland/files/0014-GLES2-gl2ext.h-Define-GL_R8_EXT-and-GL_RG8_EXT.patch
recipes-graphics/userland/files/0015-EGL-glplatform.h-define-EGL_CAST.patch
recipes-graphics/userland/files/0016-Allow-multiple-wayland-compositor-state-data-per-pro.patch
recipes-graphics/userland/files/0017-khronos-backport-typedef-for-EGL_EXT_image_dma_buf_i.patch
recipes-graphics/userland/files/0018-Add-EGL_IMG_context_priority-related-defines.patch
recipes-graphics/userland/userland_git.bb
recipes-kernel/linux/linux-raspberrypi-dev.bb
recipes-kernel/linux/linux-raspberrypi_4.19.bb

Tested with rpi3_64 wayland image, all qt5 demos work well

Add 4.19 kernel and make it default

---

recipes-kernel/linux/linux-raspberrypi_4.19.bb

linux-raspberrypi_4.19.bb: Upgrade to 4.19.25

---

recipes-kernel/linux/linux-raspberrypi_4.19.bb

linux-kernel: Upgrade to 4.9.29

---

recipes-kernel/linux/linux-raspberrypi_4.19.bb

linux-raspberrypi_4.19: Bump to 4.19.30

---

recipes-connectivity/bluez5/bluez5_%.bbappend
recipes-graphics/userland/userland_git.bb

Fixes for issues discussed here:
https://github.com/agherzan/meta-raspberrypi/commit/1317a894faa671c82193c1f18074d84db2cb9e35#commitcomment-33197660

Fix different signatures for different rpi MACHINEs which should share the same package feed

---

recipes-kernel/linux/linux-raspberrypi_4.19.bb

[Backport] linux-raspberrypi_4.19.bb: Update to 4.19.44

---

recipes-bsp/u-boot/u-boot_2019.01.bbappend

u-boot: Fix patches names in SRC_URI

---

recipes-kernel/linux/linux-raspberrypi-rt_4.19.bb
recipes-kernel/linux/linux-raspberrypi_4.19.bb
recipes-kernel/linux/linux-raspberrypi_4.19.inc

add rt kernel recipe for version 4.19
Signed-off-by: Vincenzo Pacella <shaduz@shaduzlabs.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/agherzan/meta-raspberrypi/478)

linux-raspberrypi: add linux-raspberrypi-rt 4.19

---

recipes-kernel/linux/linux-raspberrypi-rt_4.19.bb
recipes-kernel/linux/linux-raspberrypi_4.19.bb
recipes-kernel/linux/linux-raspberrypi_4.19.inc

add rt kernel recipe for version 4.19
Signed-off-by: Vincenzo Pacella <shaduz@shaduzlabs.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/agherzan/meta-raspberrypi/480)

add rt kernel recipe for version 4.19

---

recipes-kernel/linux/linux-raspberrypi_4.19.bb

linux-raspberrypi: Update 4.19 recipe to 4.19.71

---

recipes-kernel/linux/linux-raspberrypi_4.19.bb

[backport] linux-raspberrypi: Update 4.19 recipe to 4.19.71

---

recipes-kernel/linux/linux-raspberrypi-rt_4.19.bb

Signed-off-by: Vincenzo Pacella <shaduz@shaduzlabs.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/agherzan/meta-raspberrypi/507)

linux-raspberrypi-rt: Update 4.19 recipe to 4.19.71

---

recipes-multimedia/omxplayer/omxplayer_git.bb

It does not build for 64bit, needs porting

omxplayer: Disable on aarch64

---

recipes-kernel/linux/linux-raspberrypi_4.19.bb

linux-raspberrypi: bump to Linux version 4.19.93

---

recipes-bsp/armstubs/armstubs.bb
recipes-bsp/common/raspberrypi-tools.inc

Update the tools repository to current HEAD

rpi-tools update

---

README.md

README: Add documentation badge

---

conf/machine/include/rpi-base.inc
conf/machine/include/rpi-default-providers.inc
recipes-devtools/python/rpio_0.10.0.bb
recipes-graphics/userland/files/0020-openmaxil-add-pkg-config-file.patch
recipes-graphics/userland/userland_git.bb
recipes-multimedia/gstreamer/gstreamer1.0-omx_%.bbappend
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_%.bbappend

Depends on https://github.com/agherzan/meta-raspberrypi/pull/565 and http://lists.openembedded.org/pipermail/openembedded-core/2020-January/291811.html and http://lists.openembedded.org/pipermail/openembedded-core/2020-January/291812.html which are now in master-next.

gstreamer: Adjust for meson conversion

---

recipes-kernel/linux/linux-raspberrypi_4.19.bb

linux-raspberrypi: bump to Linux version 4.19.97

---

recipes-bsp/common/raspberrypi-firmware.inc

raspberrypi-firmware: bump to version 20200205

---

recipes-bsp/common/raspberrypi-firmware.inc

raspberrypi-firmware: update to current HEAD

---

recipes-graphics/mesa/files/0001-dri2-query-dma-buf-modifiers.patch
recipes-graphics/mesa/mesa_%.bbappend

Signed-off-by: balav08 <balaji.velmurugan@ltts.com>

mesa: patch for dri2_query_dma_buf_modifiers

---

recipes-kernel/linux/files/0001-selftest-bpf-Use-CHECK-macro-instead-of-RET_IF.patch
recipes-kernel/linux/linux-raspberrypi_4.19.bb

linux-raspberrypi: Fix building selftest/bpf

---

recipes-kernel/linux/linux-raspberrypi_4.19.bb

linux-raspberrypi: Get PMU fixes on top of 4.19.108

---

README.md

README.md: add status badge for raspberrypi4

---

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
recipes-graphics/userland/files/0001-Allow-applications-to-set-next-resource-handle.patch
recipes-graphics/userland/files/0002-wayland-Add-support-for-the-Wayland-winsys.patch
recipes-graphics/userland/files/0003-wayland-Add-Wayland-example.patch
recipes-graphics/userland/files/0004-wayland-egl-Add-bcm_host-to-dependencies.patch
recipes-graphics/userland/files/0005-interface-remove-faulty-assert-to-make-weston-happy-.patch
recipes-graphics/userland/files/0006-zero-out-wl-buffers-in-egl_surface_free.patch
recipes-graphics/userland/files/0007-initialize-front-back-wayland-buffers.patch
recipes-graphics/userland/files/0008-Remove-RPC_FLUSH.patch
recipes-graphics/userland/files/0009-fix-cmake-dependency-race.patch
recipes-graphics/userland/files/0010-Fix-for-framerate-with-nested-composition.patch
recipes-graphics/userland/files/0011-build-shared-library-for-vchostif.patch
recipes-graphics/userland/files/0012-implement-buffer-wrapping-interface-for-dispmanx.patch
recipes-graphics/userland/files/0013-Implement-triple-buffering-for-wayland.patch
recipes-graphics/userland/files/0014-GLES2-gl2ext.h-Define-GL_R8_EXT-and-GL_RG8_EXT.patch
recipes-graphics/userland/files/0015-EGL-glplatform.h-define-EGL_CAST.patch
recipes-graphics/userland/files/0016-Allow-multiple-wayland-compositor-state-data-per-pro.patch
recipes-graphics/userland/files/0017-khronos-backport-typedef-for-EGL_EXT_image_dma_buf_i.patch
recipes-graphics/userland/files/0018-Add-EGL_IMG_context_priority-related-defines.patch
recipes-graphics/userland/files/0019-libfdt-Undefine-__wordsize-if-already-defined.patch
recipes-graphics/userland/files/0020-openmaxil-add-pkg-config-file.patch
recipes-graphics/userland/files/0021-cmake-Disable-format-overflow-warning-as-error.patch
recipes-graphics/userland/userland_git.bb

meta-qt5 master has dropped it too

Drop xkb packageconfig and upgrade userland recipe

---

recipes-kernel/linux/linux-raspberrypi_5.4.bb

linux-raspberrypi_5.4.bb: Update to latest

---

README.md
recipes-bsp/common/raspberrypi-firmware.inc
recipes-kernel/linux/linux-raspberrypi_4.19.bb
recipes-kernel/linux/linux-raspberrypi_5.4.bb

Sync dunfell with master

---

recipes-kernel/linux/linux-raspberrypi_5.4.bb

linux-raspberrypi_5.4.bb: Move to 5.4.45

---

docs/layer-contents.md

Update layer-contents.md to include pi4.

Update layer-contents.md to include pi4

---

recipes-graphics/userland/files/0001-Allow-applications-to-set-next-resource-handle.patch
recipes-graphics/userland/files/0002-wayland-Add-support-for-the-Wayland-winsys.patch
recipes-graphics/userland/files/0003-wayland-Add-Wayland-example.patch
recipes-graphics/userland/files/0004-wayland-egl-Add-bcm_host-to-dependencies.patch
recipes-graphics/userland/files/0005-interface-remove-faulty-assert-to-make-weston-happy-.patch
recipes-graphics/userland/files/0006-zero-out-wl-buffers-in-egl_surface_free.patch
recipes-graphics/userland/files/0007-initialize-front-back-wayland-buffers.patch
recipes-graphics/userland/files/0008-Remove-RPC_FLUSH.patch
recipes-graphics/userland/files/0009-fix-cmake-dependency-race.patch
recipes-graphics/userland/files/0010-Fix-for-framerate-with-nested-composition.patch
recipes-graphics/userland/files/0011-build-shared-library-for-vchostif.patch
recipes-graphics/userland/files/0012-implement-buffer-wrapping-interface-for-dispmanx.patch
recipes-graphics/userland/files/0013-Implement-triple-buffering-for-wayland.patch
recipes-graphics/userland/files/0014-GLES2-gl2ext.h-Define-GL_R8_EXT-and-GL_RG8_EXT.patch
recipes-graphics/userland/files/0015-EGL-glplatform.h-define-EGL_CAST.patch
recipes-graphics/userland/files/0016-Allow-multiple-wayland-compositor-state-data-per-pro.patch
recipes-graphics/userland/files/0017-khronos-backport-typedef-for-EGL_EXT_image_dma_buf_i.patch
recipes-graphics/userland/files/0018-Add-EGL_IMG_context_priority-related-defines.patch
recipes-graphics/userland/files/0019-libfdt-Undefine-__wordsize-if-already-defined.patch
recipes-graphics/userland/files/0020-openmaxil-add-pkg-config-file.patch
recipes-graphics/userland/files/0021-cmake-Disable-format-overflow-warning-as-error.patch
recipes-graphics/userland/userland_git.bb

userland: Update to 2020-06-24 top commit

---

recipes-bsp/u-boot/u-boot_%.bbappend

Signed-off-by: Drew Moseley <drew.moseley@northern.tech>
Make sure bitbake can find the patch added by https://github.com/agherzan/meta-raspberrypi/pull/660
Update FILESEXTRAPATHS variable.

u-boot-rpi: Locate local patches with FILSEXTRAPATHS.

---

classes/sdcard_image-rpi.bbclass
conf/machine/include/rpi-base.inc
recipes-bsp/bootfiles/bootfiles.bb
recipes-bsp/bootfiles/rpi-config_git.bb
recipes-kernel/linux/linux-raspberrypi.inc

https://github.com/agherzan/meta-raspberrypi/pull/691 is missing in master branch.

Generalize the naming of the bootfiles deploy directory

---

docs/extra-build-config.md

Correct spelling issues in the 'extra-build-config.md' file.
Signed-off-by: Andrzej Bednarski <andrzej.bednarski@gmail.com>
Corrected spelling issues
By reading the documentation and fixing

docs: Correct minor spelling issues

---

recipes-multimedia/gstreamer/gstreamer1.0-plugins-good/0001-rpicamsrc-add-vchostif-library-as-it-is-required-to-.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.18.%.bbappend

Signed-off-by: Jose Quaresma <quaresma.jose@gmail.com>

gstreamer1.0-plugins-good: enable rpicamsrc plugin

---

recipes-graphics/mesa/libglu_%.bbappend
recipes-graphics/userland/files/0024-userland-Sync-needed-defines-for-weston-build.patch
recipes-graphics/userland/userland_git.bb

userland: Fix weston build with userland graphics

---

recipes-graphics/raspidmx/raspidmx/0001-gitignore-add-archives-from-lib-directory.patch
recipes-graphics/raspidmx/raspidmx/0002-add-install-targets-to-Makefiles.patch
recipes-graphics/raspidmx/raspidmx/0003-switch-to-pkg-config.patch
recipes-graphics/raspidmx/raspidmx/0004-add-libvchostif-to-link.patch
recipes-graphics/raspidmx/raspidmx/0005-change-library-linking-order.patch
recipes-graphics/raspidmx/raspidmx/0006-game-Makefile-install-sample-png-files.patch
recipes-graphics/raspidmx/raspidmx/0007-Makefile-reorganize.patch
recipes-graphics/raspidmx/raspidmx_git.bb

Add a recipe to build a set of dispmanx examples.
Signed-off-by: Trevor Woerner <twoerner@gmail.com>

raspidmx: add

---

.gitignore

They are generated, esepcially during test runs and selftests

gitignore: Ignore .pyc files

---

conf/machine/include/tune-arm1176jzf-s.inc

see https://github.com/kraj/meta-clang/issues/445

tune-arm1176jzf-s.inc: Rework to match oe-core

---

recipes-kernel/bluez-firmware-rpidistro/bluez-firmware-rpidistro_git.bb
recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb

Update rpi distro firmwares

---

conf/machine/include/rpi-base.inc
recipes-bsp/bootfiles/rpi-cmdline.bb
recipes-bsp/bootfiles/rpi-config_git.bb

hi, I create new PR for Raspberry Pi HD quality camera.

Add support for Raspberry Pi HD quality camera

---

conf/layer.conf
recipes-kernel/linux/linux-raspberrypi-dev.bb
recipes-kernel/linux/linux-raspberrypi_5.10.bb
recipes-kernel/linux/linux-raspberrypi_5.4.bb

All 4 commits in master are backwards compatible with hardknott.
Please fast-forward hardknott to master branch.

[hardknott] Backports from master

---

recipes-connectivity/pi-bluetooth/pi-bluetooth/0001-bthelper-correct-path-for-hciconfig-under-Yocto.patch
recipes-connectivity/pi-bluetooth/pi-bluetooth_0.1.17.bb

* synced meta-raspi-light ro meta-raspberrypi in wide areas
* tested Bluetooth on Raspi4: search / pair / stream / switch on/off
* cherry-picked this patch back to meta-raspberrypi
??

pi-bluetooth: upgrade 0.1.12 -> 0.1.17

---

recipes-bsp/common/raspberrypi-firmware.inc

Update raspberrypi firmware to 20210527
Fixes #878
Signed-off-by: Omer Akram omer@thing.com

Update raspberrypi firmware to 20210527

---

recipes-devtools/python/python3-adafruit-blinka_6.2.2.bb
recipes-devtools/python/python3-adafruit-circuitpython-busdevice_5.0.5.bb
recipes-devtools/python/python3-adafruit-circuitpython-motor_3.2.6.bb
recipes-devtools/python/python3-adafruit-circuitpython-motorkit_1.6.1.bb
recipes-devtools/python/python3-adafruit-circuitpython-pca9685_3.3.4.bb
recipes-devtools/python/python3-adafruit-circuitpython-register_1.9.4.bb
recipes-devtools/python/python3-adafruit-platformdetect_3.1.1.bb
recipes-devtools/python/python3-adafruit-pureio_1.1.8.bb

* master branch was renamed to main

python3-adafruit-*: fix branch parameter

---

recipes-devtools/python/python3-adafruit-blinka_6.2.2.bb
recipes-devtools/python/python3-adafruit-circuitpython-busdevice_5.0.5.bb
recipes-devtools/python/python3-adafruit-circuitpython-motor_3.2.6.bb
recipes-devtools/python/python3-adafruit-circuitpython-motorkit_1.6.1.bb
recipes-devtools/python/python3-adafruit-circuitpython-pca9685_3.3.4.bb
recipes-devtools/python/python3-adafruit-circuitpython-register_1.9.4.bb
recipes-devtools/python/python3-adafruit-platformdetect_3.1.1.bb
recipes-devtools/python/python3-adafruit-pureio_1.1.8.bb

* master branch was renamed to main

[hardknott] python3-adafruit-*: fix branch parameter

---

recipes-devtools/python/python3-adafruit-blinka_6.2.2.bb
recipes-devtools/python/python3-adafruit-circuitpython-busdevice_5.0.5.bb
recipes-devtools/python/python3-adafruit-circuitpython-motor_3.2.6.bb
recipes-devtools/python/python3-adafruit-circuitpython-motorkit_1.6.1.bb
recipes-devtools/python/python3-adafruit-circuitpython-pca9685_3.3.4.bb
recipes-devtools/python/python3-adafruit-circuitpython-register_1.9.4.bb
recipes-devtools/python/python3-adafruit-platformdetect_3.1.1.bb
recipes-devtools/python/python3-adafruit-pureio_1.1.8.bb

* master branch was renamed to main

[gatesgarth] python3-adafruit-*: fix branch parameter

---

docs/extra-build-config.md
recipes-bsp/bootfiles/rpi-config_git.bb

Allow setting hdmi_cvt from rpi-config

rpi-config: Allow setting hdmi_cvt

---

conf/machine/raspberrypi-cm3.conf
conf/machine/raspberrypi2.conf
conf/machine/raspberrypi3-64.conf
conf/machine/raspberrypi3.conf
conf/machine/raspberrypi4-64.conf
conf/machine/raspberrypi4.conf

machines: Use tune files from renamed location in core

---

recipes-bsp/common/raspberrypi-firmware.inc
recipes-kernel/linux/linux-raspberrypi_5.10.bb

- firmware bumped to 20211007
- linux-raspberrypi to 5.10.76

Kernel and firmware update

---

conf/machine/raspberrypi0-2w-64.conf
recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
recipes-kernel/linux/linux-raspberrypi_5.10.bb

**- What I did**: Added Pi Zero 2 Wireless machines and firmware package
**- How I did it**:  Used the existing Pi3 machines configurations
Connects-to: https://github.com/agherzan/meta-raspberrypi/issues/929

Add Pi Zero 2 W

---

recipes-bsp/bootfiles/rpi-config_git.bb

Also, validate if the value of it is not 0 or 1.
Fixes: https://github.com/agherzan/meta-raspberrypi/issues/567

rpi-config: Take into consideration ENABLE_UART value of 0

---

recipes-kernel/linux/linux-raspberrypi_5.10.bb

linux-raspberrypi: Upgrade to 5.10.83

---

docs/extra-build-config.md

Signed-off-by: Jan Vermaete <jan.vermaete@gmail.com>

docs: untabify the few tabs in the file

---

docs/extra-build-config.md

remove unneeded markdown from M8960 soundcard support.
Signed-off-by: Vincent Davis Jr <vince@underview.tech>

docs: remove backticks

---

recipes-bsp/common/raspberrypi-firmware.inc

Signed-off-by: Vinicius Aquino <vinicius.aquino@ossystems.com.br>
(cherry picked from commit 9ea5daf9fcfe7c5c95c68a6df552b817d2b6aced)

raspberrypi-firmware: Update to 20220830 snapshot

---

.github/actions/docker-build/action.yml
.github/workflows/yocto-builds.yml
.github/workflows/yocto-layer.yml

Fix two randomly spotted issues (typo and apparent typo). Please verify the 2nd patch.

Drive-by fixes

---

.github/workflows/docker-images/yocto-builder/entrypoint-build.sh
docs/conf.py
docs/requirements.txt
recipes-multimedia/omxplayer/omxplayer_git.bb

This fixes:
- usrmerge requirement in upstream for systems builds
- docs failing when no HTML theme is set

Various fixes

---

conf/machine/include/rpi-base.inc
conf/machine/include/rpi-default-versions.inc
recipes-bsp/common/raspberrypi-firmware.inc
recipes-kernel/bluez-firmware-rpidistro/bluez-firmware-rpidistro_git.bb
recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
recipes-kernel/linux/linux-raspberrypi-v7_6.6.bb
recipes-kernel/linux/linux-raspberrypi_6.6.bb
recipes-multimedia/picamera-libs/picamera-libs.bb

Upgrade to 6.6 kernel

---

README.md

Updated a stale link to yocto project compatible layers in the README
Used upated link

Update stale link

---

.github/workflows/compliance.yml
.github/workflows/docker-images/yocto-builder/Dockerfile
.github/workflows/yocto-builds.yml
.github/workflows/yocto-layer.yml

Fixes the issue that affects https://github.com/agherzan/meta-raspberrypi/pull/1390#issuecomment-2800882366:
```
RuntimeError: Sorry, python 3.9.0 or later is required for this version of bitbake
```
Upgrade to Ubuntu 22.04 because it is compatible with the Yocto Project release Walnascar and provides a newer Python version.

yocto-builder/Dockerfile: Ubuntu 22.04
