agherzan/meta-raspberrypi

recipes-kernel/linux/linux-raspberrypi_4.9.bb
This is a backport of Khem's patch from master. Boot tested on a raspberrypi (Model B+) and raspberrypi3.
=> linux-raspberrypi_4.9.bb: Update to 4.9.23

conf/machine/raspberrypi0.conf, recipes-kernel/linux/linux-raspberrypi.inc
currently there is no way to override the default CMDLINE, lets set if only if not already set from outside
=> Make CMDLINE overridable from outside

recipes-kernel/linux/linux-raspberrypi_4.9.bb
Boot tested on raspberrypi (Model B+) and raspberrypi3.
=> linux-rasbperrypi: Update to 4.9.27 and minor tidyup

recipes-devtools/bcm2835/bcm2835_1.52.bb
By default, the ${PN}-dev package of a recipe depends on the ${PN}
package.  However, since the bcm2835 package contains no file, it is not
generated.  As a result, when trying to include bcm2835-dev in an image
(or another package that depends on bcm2835-dev, such as
bcm2835-staticdev), we receive an error message saying that the bcm2835
package is not found.
A solution would be to define ALLOW_EMPTY for bcm2835, so that an empty
package is generated.  However, that would causes a useless package to
be installed on the target.  This patch uses another solution, which is
to empty the RDEPENDS variable of bcm2835-dev, so that it doesn't pull
in bcm2835.
Fixes #22
Signed-off-by: Simon Marchi <simon.marchi@polymtl.ca>
=> bcm2835: Remove dependency of bcm2835-dev on bcm2835

README, recipes-kernel/linux/linux-raspberrypi_4.9.bb
* Backport linux-raspberrypi v4.9.27 upgrade.
* Update README to point contributors at GitHub pull requests.
Boot tested on raspberrypi (Model B+), raspberrypi3 and raspberrypi3-64.
=> [morty] Backport kernel upgrage and update readme

recipes-kernel/linux/linux-raspberrypi-dev.bb
Using ${AUTOREV} requires network access to run 'git ls-remote' and causes parsing to fail if BB_NO_NETWORK is set to 1. So we need to avoid having to resolve ${AUTOREV} for builds which include the meta-raspberrypi layer but don't actually use the linux-raspberrypi dev branch recipe.
We can do this by renaming the recipe to linux-raspberrypi-dev so that it is a separate provider of virtual/kernel. Then we can skip the recipe unless it is selected as the preferred provider of virtual/kernel.
=> Allow network traffic to be avoided unless development kernel recipe is selected

recipes-devtools/pi-blaster/files/remove-initscript-lsb-dependency.patch, recipes-devtools/pi-blaster/pi-blaster.inc, recipes-devtools/pi-blaster/pi-blaster_git.bb
Update to latest available revision, in order to include proper rpi3
support as well as latest fixes.
Signed-off-by: Petter Mabäcker <petter@technux.se>
=> pi-blaster: update to include proper rpi3 support

classes/sdcard_image-rpi.bbclass
This is useful to update the bootloader/vfat partition from u-boot when
you don't want to update everything:
U-Boot> tftpboot 0x1000000 tmp/0VXje
Waiting for Ethernet connection... done.
Using sms0 device
TFTP from server 192.168.0.1; our IP address is 192.168.0.26
Filename 'image.vfat'.
Load address: 0x1000000
Loading: ##################################################  40 MiB
2.1 MiB/s
done
Bytes transferred = 41943040 (2800000 hex)
U-Boot> mmc part
Partition Map for MMC device 0  --   Partition Type: DOS
Part	Start Sector	Num Sectors	UUID		Type
1	8192      	81920     	a63a4fbc-01	0c Boot
2	90112     	163840    	a63a4fbc-02	83
U-Boot> mmc erase 0x2000 0x14000
MMC erase: dev # 0, block # 8192, count 81920 ... 81920 blocks erased:
OK
U-Boot> mmc write 0x1000000 0x2000 0x14000
MMC write: …
=> sdcard_image-rpi.bbclass: deploy vfat partition

conf/machine/include/rpi-base.inc
This commit allow wic generated images to work when we want u-boot to
load the kernel image.
Augment IMAGE_BOOT_FILES with the proper entries when KERNEL_IMAGETYPE
is "uImage". More specifically add u-boot image and boot.scr to deployed files
and give the proper name to the kernel image accordingly.
Signed-off-by: Andrea Galbusera <gizero@gmail.com>
=> rpi-base: wic: generate entries for u-boot

recipes-kernel/linux/linux-raspberrypi-dev.bb
=> linux-raspberrypi-dev: Switch to rpi-4.12.y

recipes-graphics/userland/userland/0015-EGL-glplatform.h-define-EGL_CAST.patch, recipes-graphics/userland/userland_git.bb
Recent updates of libepoxy in oe-core broke the build for raspberrypi of dependent packages like gtk+3, due to a missing definition in an glplatform.h header provided by userland.
This patch backports the missing define from the updated version of the header available in mesa, hence restoring successful builds.
The patch has been submitted upstream here: https://github.com/raspberrypi/userland/pull/407
See http://lists.openembedded.org/pipermail/openembedded-core/2017-July/139311.html for relevant discussions.
=> userland: Add missing EGL_CAST defines

recipes-bsp/common/firmware.inc, recipes-kernel/linux/linux-raspberrypi_4.9.bb
Both the Linux kernel and the rpi firmware are updated to the latest tags dated 2017-08-11.
=> Update kernel & firmware

classes/sdcard_image-rpi.bbclass
Fix bitbake complaining with:
ERROR: core-image-minimal-1.0-r0 do_image_complete: sstate found an absolute
path symlink [...].vfat pointing at [...].vfat. Please replace this with a
relative link.
Signed-off-by: Andrea Galbusera <gizero@gmail.com>
=> sdcard_image-rpi: fix absolute path in vfat symlink

docs/extra-build-config.md, recipes-kernel/linux/linux-raspberrypi.inc
Signed-off-by Zdzisław Krajewski <zdzichucb@gmail.com>
I added option for removing rpi logo from boot screen.
I added line in `recipes-kernel/linux/linux-raspberrypi-dev.bb` which appends `logo.nologo` option to `/boot/cmdline.txt` file according to `DISABLE_RPI_BOOT_LOGO` variable.
=> linux-raspberrypi: Add option for disabling rpi boot logo.

conf/machine/raspberrypi3-64.conf
The current setup broke the build for rpi3-64 when we wanted to port
some changes from rpi3 to rpi0.
=> raspberrypi3-64.conf: Don't use raspberrypi as MACHINEOVERRIDES

recipes-devtools/wiringPi/files/0001-Add-initial-cross-compile-support.patch
[github issue #105: wiringpi library is not linked correctly]
Incorrect order of compiler flags causing the libwiringpi.so library
to not have the required linking dependencies. The cross-compilation
patch needed to be reworked in order to fix this problem.
Fixes #105
Signed-off-by: Aurelian Zanoschi <aurelian17@gmail.com>
The major problems were in the Makefile from wiringPi source tree that is currently patched by 0001-Add-initial-cross-compile-support.patch. I had to fix the problems and rework the patch on Pyro branch.
=> wiringpi: Fix linking problem

conf/layer.conf, dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
This allow for bbappend files to be enabled when specific layers are
included.
Change-Id: I9f2ebbbc19a343946f19c898a6576714ba0d803c
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
=> Add Dynamic Layer mechanism

recipes-kernel/linux/linux-raspberrypi.inc
Signed-off-by: Andrei Gherzan <andrei@gherzan.com>
Define the defconfig for RPI- WiFi
=> linux-raspberrypi.inc: Define KBUILD_DEFCONFIG for rpi0 WiFi

recipes-bsp/bootfiles/rpi-config_git.bb, recipes-kernel/linux/linux-raspberrypi.inc
These changes fix the HDMI output issues I've been facing with raspberrypi3-64 and a DVI monitor (connected via a HDMI to DVI cable).
=> Fix HDMI output issues on raspberrypi3-64

docs/extra-apps.md
Graphical output on raspberrypi3-64 should now be fixed.
=> Drop comment on broken raspberrypi3-64 HDMI output

classes/sdcard_image-rpi.bbclass, conf/machine/include/rpi-base.inc, recipes-kernel/linux/linux-raspberrypi_4.9.bb
The following changes from master are backported:
* Update linux-raspberrypi to v4.9.50.
* Fix path used in symlink when deploying the vfat boot partition image.
* Fix wic image creation.
=> Backports for pyro

recipes-graphics/wayland/weston_%.bbappend
rpi-backend.so was an attempt to create a specialized
weston backend to be used on raspberry pi like platforms.
At the moment, this backend's support has been dropped in favor
of using the standard drm backend, as the vc4 driver is now mainline
in mesa and in kernel (for kernel support).
As a result, weston on raspberry pi does not require the rpi-backend.so
anymore, nor it is buildable (weston's configure complains about
unrecognized configuration switch).
This patch enables weston to natively run on the DRM backend.
Signed-off-by: Francesco Giancane <francescogiancane8@gmail.com>
=> weston: remove rpi-backend configuration switch

recipes-graphics/userland/userland_git.bb
If selected, it shall provide the gles2 and egl stacks in conjunction
with mesa-gl.
libegl was missing in the RPROVIDES variable, thus some run-time
dependencies were not met when using userland as provider.
Signed-off-by: Francesco Giancane <francescogiancane8@gmail.com>
=> userland package is the Raspberry Pi 3 provider for the openGL stack.

conf/machine/include/rpi-base.inc, conf/machine/raspberrypi3-64.conf
Fix: 50fd319205d8 for raspberrypi3-64.
Set default kernel image to "Image" because compressed images "zImage"
are not supported by arm64 platforms.
".gz" images are not handled by bootloader yet.
Signed-off-by: Loys Ollivier <lollivier@baylibre.com>
=> Fix raspberrypi3-64 kernel Image.

conf/machine/include/rpi-base.inc, conf/machine/raspberrypi3-64.conf
We can't just override KERNEL_IMAGETYPE in machine-specific conf files without
breaking the implementation of RPI_USE_U_BOOT. Instead we need to define a new
KERNEL_IMAGETYPE_DIRECT variable which will control the value when u-boot is not
in use. This new variable may then be overridden as needed without breaking our
u-boot support.
=> rpi-base.inc: Fix KERNEL_IMAGETYPE assignment

README.md, docs/conf.py, docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-config_git.bb, recipes-graphics/userland/userland_git.bb
* Update quick links in readme
* Add RPI_EXTRA_CONFIG option (#169)
* Use commit date as package version in userland (as discussed on 9b1a796c)
* Allow Read the Docs to use their default theme for the documentation
=> Minor tweaks

conf/machine/raspberrypi0-wifi.conf, recipes-bsp/u-boot/u-boot/0001-add-support-for-Raspberry-Pi-Zero-W.patch, recipes-bsp/u-boot/u-boot/0002-rpi_0_w-Add-configs-consistent-with-RpI3.patch, recipes-bsp/u-boot/u-boot_%.bbappend
This series adds U-boot support for RPi Zero W.
It contains one back-ported patch from upstream U-boot which adds initial support for RPi Zero W, and it contains a patch from @drewmoseley that fixes an issue with DTB forwarding (this patch has also been sent upstream).
I do not have this board and @drewmoseley has helped out testing this series. Further testing is welcome.
This pull-request is based on discussion from #160
=> U-boot support for RPi Zero W

recipes-bsp/bootfiles/rpi-config_git.bb
Allow user to replace VC4DTBO (e.g. vc4-kms-v3d) on raspberrypi3-64.
Signed-off-by: Ricardo Salveti <ricardo@opensourcefoundries.com>
=> rpi-config: allow VC4DTBO override on raspberrypi3-64

conf/machine/include/rpi-base.inc
The kernel class is now using $KERNEL_PACKAGE_NAME to set the default
kernel package name in order to allow alternate kernel flavors.
This fixes the following bitbake warning:
Variable key RDEPENDS_${KERNEL_PACKAGE_NAME}-base (${KERNEL_PACKAGE_NAME}-image) replaces original key RDEPENDS_kernel-base ().
Signed-off-by: Ricardo Salveti <ricardo@opensourcefoundries.com>
=> rpi-base.inc: use $KERNEL_PACKAGE_NAME for the kernel package name

recipes-kernel/linux-firmware/linux-firmware_%.bbappend
Currently, we are installing the rpi custom txt and fw files whenever
the meta-raspberrypi layer is included in bblayers.conf. This breaks
other machines that need to use the bcm43430 drivers but with alternate
txt or fw files.
Add a MACHINE_FEATURE rpi-bcm43430 and make the linux-firmware.bbappend
conditional upon it. This is not pretty, but it does work and I don't
see a cleaner way to do it.
Signed-off-by: Martin Kelly <mkelly@xevo.com>
=> linux-firmware: make rpi fw specific to rpi

recipes-kernel/linux/linux-raspberrypi.inc
Currently, building linux-raspberrypi with "devtool build" breaks
because the do_configure_prepend function assumes that ${S} == ${B}.
Thus it tries to touch ${B}.config, but ${B}.config does not exist yet.
${S}.config. It will get created in the kernel_do_configure function in
kernel.bbclass, but that code hasn't happened yet.
Thus the correct workflow is:
(1) Copy ${WORKDIR}/defconfig to ${B}.config
(2) Tweak ${B}.config
(3) Run configure
Since we need to add (2) in between (1) and (3), and since (1) and (3)
are in kernel_do_configure (in kernel.bbclass), there's no good way to
use prepend or append. So, we add step (1) at the start of (2).
This fixes #49.
Signed-off-by: Martin Kelly <mkelly@xevo.com>
=> linux-raspberrypi: fix build with devtool

recipes-kernel/linux-firmware/linux-firmware_%.bbappend
This PR fixes #184, where the Wifi module is not brought up because of missing firmware file.
The NVRAM text file for the BCM firmware was not properly added in the built image. This is because the recipe `recipes-kernel/linux-firmware/linux-firmware_%.bbappend` is using `+=` for adding the extra file instead of `_append` in `FILES_${PN}-bcm43430`.
This results in only the NVRAM text file being added to the built image and not the firmware binary file (`.bin`), causing the Wifi module to not work.
I tested the images also enabling the bluetooth module (as discussed in #184) to ensure this doesn't interfere with other connectivity components.
After this fix, both files (`.txt` and `.bin`) of the firmware are now correctly installed in `/lib/firmware`.
I …
=> linux-firmware: fix addition of NVRAM file to image (fixes #184)

recipes-bsp/u-boot/u-boot/0002-rpi_0_w-Add-configs-consistent-with-RpI3.patch, recipes-bsp/u-boot/u-boot_%.bbappend
This makes the defconfig more consistent with the RPi 3 and
CONFIG_OF_EMBED is needed to get the RPi firmware provided
DTB to function.
Recently removed by:
a50e19695f2cc655ef6248b77c8244519dbb468c u-boot: drop upstreamed patches in v2018.01
however this change missed the cutoff for v2018.01
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>
=> u-boot: Update RPi Zero W defconfig to support DTB.

classes/sdcard_image-rpi.bbclass, conf/machine/include/rpi-base.inc, conf/machine/include/rpi-default-versions.inc, recipes-bsp/common/firmware.inc, recipes-core/images/rpi-basic-image.bb, recipes-core/images/rpi-hwup-image.bb, recipes-core/images/rpi-test-image.bb, recipes-devtools/python/rpio_0.10.0.bb, recipes-kernel/linux/linux-raspberrypi-dev.bb, recipes-kernel/linux/linux-raspberrypi_4.14.bb, recipes-kernel/linux/linux-raspberrypi_4.9.bb
* Fix do_image_rpi_sdimg/do_image_wic dependencies
* rpio: Use pypi.bbclass
* rpi-*-image: Deprecate old image names
* Update kernels to 4.9.80, 4.14.22, 4.15.y
* Update firmware
* Switch default kernel to 4.14.y series
Tested a mix of different distros, images, configurations (with/without u-boot, 4.9.y/4.14.y kernels, etc) and devices (original rpi, rpi2, rpi3, rpi-64). All boots to a login prompt happily :)
=> Kernel updates and other improvements

recipes-devtools/python/rpio_0.10.0.bb
This should resolve recent issues with the non-https URL in SRC_URI. 
fixes #146
Signed-off-by: Paul Barker <pbarker@toganlabs.com>
=> rpio: Use pypi.bbclass

conf/machine/include/rpi-base.inc, wic/sdimage-raspberrypi.wks
Many kickstart files used `--on mmcblk` for SD builds, which produces the image but breaks runtime now that wic no longer excludes /boot from the set of partitions added to fstab for mount on boot.  The first commit patches the raspberrypi kickstart file to set the correct device.
The second  commit simply provides a default for `WKS_FILE`, to make it simpler for people to add wic as an image fstype in `local.conf` as with:
IMAGE_FSTYPES_append = " wic wic.bmap"
=> patches to improve wic support

README.md, docs/layer-contents.md
This finishes the remaining tasks in #199.
=> docs: Remove reference to deprecated images

wic/sdimage-raspberrypi.wks
Recently wic was modified to no longer exclude /boot from partitions
added to fstab.  The --on parameter in many kickstart specifications
insufficiently resolved the MMC device, resulting in attempts to mount
/dev/mmcblkp1 as boot when the device should be /dev/mmcblk0p1.
With systemd the mount failure is an error and the system drops into
emergency mode.
Signed-off-by: Peter A. Bigot <pab@pabigot.com>
(cherry picked from commit 0e1e2c6e0aebab8a7536f81dc25f50c0f2f6d518)
Signed-off-by: Phong Tran <tranmanphong@gmail.com>
For fixing the /boot partition with wic image.
Cherry pick from 0e1e2c6 
build and boot fine with AGL distro on rpi3
=> sdimage-raspberrypi.wks: find /boot partition on mmcblk0

docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-config_git.bb
Added support for and documented the following new extra build options:
* gpu_freq overclocking option
* disable boot rainbow splash screen
* configure the boot delay after GPU firmware loading
* configure common HDMI and composite video options
Implemented new config.txt options in the `rpi-config` recipe.
Followed the same logic in the recipe and added new supported options.
Also updated the documentation.
=> rpi-config: support more commonly used config variables and update documentation

recipes-bsp/bootfiles/bcm2835-bootfiles.bb, recipes-bsp/bootfiles/rpi-config_git.bb, recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr.bb, recipes-bsp/u-boot/u-boot_%.bbappend, recipes-core/udev/udev-rules-rpi.bb, recipes-core/udev/udev-rules-udisks-rpi_1.0.bb, recipes-graphics/vc-graphics/vc-graphics.inc, recipes-kernel/linux-firmware/linux-firmware-raspbian.bb, recipes-kernel/linux/files/0001-menuconfig-check-lxdiaglog.sh-Allow-specification-of.patch, recipes-kernel/linux/linux-raspberrypi-dev.bb, recipes-kernel/linux/linux-raspberrypi.inc, recipes-kernel/linux/linux-raspberrypi_4.14.bb, recipes-kernel/linux/linux-raspberrypi_4.9.bb
* Apply patch to fix `bitbake linux-raspberrypi -c menuconfig` on distros where the native ncurses differs from the one we build. Discussed on oe-core list here: http://lists.openembedded.org/pipermail/openembedded-core/2018-April/149912.html
* Updates for all our kernel recipes.
* Drop unnecessary dependencies and tasks from a few recipes.
* Switch from RDEPENDS to DEPENDS for recipes which don't create a package.
* Major cleanup of kernel `do_configure_prepend` function. Everything has been reviewed against the kernel config created when running `make bcmrpi_defconfig` and `make bcm2709_defconfig` for `ARCH=arm` and `make bcmrpi3_defconfig` for `ARCH=arm64` in the linux-raspberrypi sources. I've kept all settings which appear to be functional and not horrifically obsolete.
I'm hoping …
=> Kernel updates, removal of obsolete config and dependency/task cleanup

classes/sdcard_image-rpi.bbclass
Only a small typo on bbclass header.
=> bbclass: Fix a typo in comment

conf/machine/include/rpi-base.inc, docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-config_git.bb
When initially provisioning a headless device it's nice to be able to connect it to a computer using USB networking.  This requires using a USB driver that understands peripheral (gadget) mode.  These patches add the required dt overlay and provide a short-hand to add it to config.txt.
=> simplify use of usb gadget mode

recipes-graphics/wayland/wayland_%.bbappend
Wayland was updated recently in Poky, and now includes `libwayland-egl`:
commit 8097bf7012a0d97d3b8b48eceb5dc20cc4ae7ca9
Author: Denys Dmytriyenko <denys@ti.com>
Date:   Tue Apr 10 15:06:09 2018 -0400
wayland: upgrade to 1.15.0
Official announcement:
https://lists.freedesktop.org/archives/wayland-devel/2018-April/037767.html
| libwayland-egl is now part of libwayland, and will presumably be removed
| from mesa in the not too distant future.
Update mesa recipe by removing corresponding libwayland-egl entries.
(From OE-Core rev: 6e5952fcfc13ff4b63c9376bd41a1dbba957f425)
Signed-off-by: Denys Dmytriyenko <denys@ti.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
However, the `userland` ships its own version of the …
=> wayland: do not install libwayland-egl from wayland

recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_%.bbappend
1.14 does not support this option
Fixes
QA Issue: gstreamer1.0-plugins-bad: configure was passed unrecognised options: --disable-dispmanx [unknown-configure-option]
=> gstreamer1.0-plugins-bad_%.bbappend: Drop --disable-dispmanx

recipes-graphics/userland/userland/0017-khronos-backport-typedef-for-EGL_EXT_image_dma_buf_i.patch, recipes-graphics/userland/userland_git.bb
The `gstreamer1.0-plugins-base` package version `1.14` uses `EGL_EXT_image_dma_buf_import`, which
expects the `EGLuint64KHR` typedef that is present in recent versions of Khronos.
However, the older version included in userland does not provide it.
This patch backports the missing typedef from recent Khronos into userland.
See: <https://www.khronos.org/registry/EGL/api/EGL/eglext.h>
Related to PR #247 and Issue #243
=> userland: bumped version and backport khronos typedef for EGL_EXT_image_dma_buf_import

conf/machine/raspberrypi3-64.conf, recipes-bsp/bootfiles/rpi-config_git.bb
This resolves #253 on sumo and has been tested.
It is not sufficient by itself to address #251 as #254 must also be resolved (I made this change by hand for testing).
=> sumo: fix firmware support on aarch64

recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_%.bbappend, recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_%.bbappend
This patch accounts for the fact that rpi dispmanx plugin migrated
from bad to base stating 1.14 release
should fix
https://github.com/agherzan/meta-raspberrypi/pull/250#issuecomment-390263798
=> gstreamer1.0-plugins: App proper appends for base and bad plugins

recipes-graphics/userland/userland/0017-khronos-backport-typedef-for-EGL_EXT_image_dma_buf_i.patch
The patch in 237e0c7 used a define guard that clashes with an actual feature of Khronos (EGL_KHR_stream).
This makes some packages such as `qtbase` to think that the outdated Krhonos in userland has newer features.
This fix uses a more specific name for the relevant define guard (EGL_KHR_uint64_typedef).
Fixes #273
=> userland: fix backport khronos typedef patch

classes/sdcard_image-rpi.bbclass
These are bits from older PR:
https://github.com/agherzan/meta-raspberrypi/pull/159
without the dependency on oe-core changes which weren't merged yet.
The files in deploy/raspberrypi3 are the same:
$ diff -rq */deploy/images/*/
Only in old/deploy/images/raspberrypi3/: rpi-hwup-image-raspberrypi3-20180702120324.testdata.json
Only in old/deploy/images/raspberrypi3/: rpi-hwup-image-raspberrypi3-20180702141536.rootfs.ext3
Only in old/deploy/images/raspberrypi3/: rpi-hwup-image-raspberrypi3-20180702141536.rootfs.manifest
Only in old/deploy/images/raspberrypi3/: rpi-hwup-image-raspberrypi3-20180702141536.rootfs.rpi-sdimg
Only in old/deploy/images/raspberrypi3/: rpi-hwup-image-raspberrypi3-20180702141536.testdata.json
Only in old/deploy/images/raspberrypi3/: …
=> sdcard_image-rpi.bbclass improvements

classes/sdcard_image-rpi.bbclass, docs/extra-build-config.md, recipes-kernel/linux/linux-raspberrypi.inc
* use INITRAMFS_SYMLINK_NAME from new kernel-artifact-names.bbclass
instead of KERNEL_INITRAMFS
* the documentation says that KERNEL_INITRAMFS should be used to
define extension of initramfs, but in linux-raspberrypi.inc it's
defined only to 1 or empty based on INITRAMFS_IMAGE_BUNDLE variable
and I don't see any code in meta-raspberry or oe-core which would
use KERNEL_INITRAMFS to actualy name the initramfs artifact to create:
${DEPLOY_DIR_IMAGE}/${KERNEL_IMAGETYPE}${KERNEL_INITRAMFS}-${MACHINE}.bin
used in classes/sdcard_image-rpi.bbclass
* also fix the assumption that there is -${MACHINE} suffix in:
${DEPLOY_DIR_IMAGE}/${KERNEL_IMAGETYPE}${KERNEL_INITRAMFS}-${MACHINE}.bin
because that's defined as KERNEL_IMAGE_SYMLINK_NAME and some DISTROs
might use different value
* this depends on …
=> sdcard_image-rpi.bbclass: drop KERNEL_INITRAMFS variable

conf/machine/raspberrypi-cm3.conf
The CM3 module is based Raspberry Pi 3 not 2.
Signed-off-by: Andrei Gherzan <andrei@gherzan.com>
=> raspberrypi-cm3.conf: Inherit raspberrypi3 not raspberrypi2

conf/machine/raspberrypi3-64.conf
Add the CM3 dtb in the boot partition so we can boot this board as well with
this machine.
Signed-off-by: Andrei Gherzan <andrei@gherzan.com>
=> raspberrypi3-64.conf: Include cm3 dtb

conf/machine/include/rpi-base.inc
[Issue #285] -- https://github.com/agherzan/meta-raspberrypi/issues/285
The openembedded-core commit 1860d9d3c62e2e94cd68a809385873ffd8270b6d
changed the names of DTB files in the deploy directory - they are no
longer prefixed with "${KERNEL_IMAGETYPE}-". Update make_dtb_boot_files
(which generates entries in IMAGE_BOOT_FILES) to take this change into
account.
Signed-off-by: Jonathan Haigh <jonathan.haigh@arm.com>
=> rpi-base.inc: update IMAGE_BOOT_FILES for change in oe-core

recipes-kernel/linux/linux-raspberrypi_4.9.bb
Contains the following changes:
7f9c648dad64 drm/vc4: Move IRQ enable to PM path
which fixes an unbalanced IRQ enable warning, which was rapported
in #286
Signed-off-by: Mirza Krak <mirza.krak@northern.tech>
Signed-off-by: Gunnar Andersson <gandersson@genivi.org>
=> linux-raspberrypi: update 4.9 recipe to current HEAD

recipes-kernel/linux-firmware/linux-firmware_%.bbappend
* this will make this bbappend a bit more version agnostic
* depends on oe-core commits from:
http://lists.openembedded.org/pipermail/openembedded-core/2018-July/153164.html
to prevent including ${PN}-cypress-license package twice in PACKAGES
http://lists.openembedded.org/pipermail/openembedded-core/2018-July/153165.html
=> linux-firmware: move ${PN}-cypress-license handling to oe-core recipe

recipes-kernel/linux-firmware/linux-firmware_%.bbappend
This is the rest of https://github.com/agherzan/meta-raspberrypi/pull/295 it also depends on oe-core changes which aren't in master yet, but as of today they are in master-next.
http://lists.openembedded.org/pipermail/openembedded-core/2018-July/153164.html
http://lists.openembedded.org/pipermail/openembedded-core/2018-July/153167.html
=> linux-firmware: remove duplicate ${PN}-bcm43455 package

recipes-devtools/wiringpi/files/0001-Add-initial-cross-compile-support.patch, recipes-devtools/wiringpi/wiringpi_git.bb
Updated wiringpi to v2.46 to support the RPi 3 B+.
Updated the wiringpi commit to 2.46.
Applied the patch for 2.44, then rebased to 2.46.
Tested on RPi 3 B and RPi 3 B+, using the gpio command to set an LED pin's mode to output and writing to it.
=> wiringpi: uprev to 2.46

classes/sdcard_image-rpi.bbclass
${INITRAMFS_SYMLINK_NAME} has been changed to ${INITRAMFS_LINK_NAME} in
poky's commit f09947586c5c2c05368651838fea970808ab161d
Updated the variable names in poky's master
I have not tested the `INITRAMFS_IMAGE_BUNDLE` end-to-end but there is no chance for it to work without using the same variable names as in poky.
=> sdcard_image-rpi: fix kernel artifacts variables

recipes-core/packagegroups/packagegroup-rpi-test.bb, recipes-multimedia/omxplayer/omxplayer/0001-Specify-cc-cxx-and-ld-variables-from-environment.patch, recipes-multimedia/omxplayer/omxplayer/0001-openssl-Support-version-1.1.0.patch, recipes-multimedia/omxplayer/omxplayer/0001-rtmpdh-Stop-using-OpenSSL-provided-DH-functions-to-s.patch, recipes-multimedia/omxplayer/omxplayer/0001-swresample-arm-avoid-conditional-branch-to-PLT-in-TH.patch, recipes-multimedia/omxplayer/omxplayer_git.bb
* Update to latest from upstream
* Backport OpenSSL 1.1.x related patches for ffmpeg
* Pass --cpu based on machine, instead of hardcoding it to arm1176jzf-s
* Make --cc, --cxx and --ld be used from environment, helps building
with clang
* It requires userland graphics driver to build to encode that in
COMPATIBLE_HOST
=> omxplayer: Update and add fixes for OpenSSL 1.1.x and thumb2

recipes-graphics/mesa/mesa_%.bbappend, recipes-graphics/xorg-xserver/xserver-xf86-config/rpi/xorg.conf.d/10-noglamor.conf, recipes-graphics/xorg-xserver/xserver-xf86-config_%.bbappend
when running -ctestimage target, it fails because of errors it finds in
Xorg logs
| Log:
/mnt/a/yoe/build/tmp/work/raspberrypi3-yoe-linux-gnueabi/core-image-sato/1.0-r0/target_logs/Xorg.0.log
| -----------------------
| Central error: [    14.760] (EE) AIGLX error: dlopen of /usr/lib/dri/swrast_dri.so failed (/usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory)
Therefore we enable swrast gallium drivers to make xorg happy
=> mesa: Build swrast gallium driver along with vc4

recipes-bsp/bootfiles/rpi-config_git.bb
vc4-fkms-v3d needs dispmanx, its DRM VC4 V3D driver on top of the dispmanx
display stack, this does not work with 4.14 kernel and since we always
use vc4graphics on 64bit, just keep using vc4-kms-v3d dtbo which should
enable right graphics
Tested with core-image-sato, running glxgears with 55.5fps in
raspberrypi3-64
=> rpi-config: Use vc4-kms-v3d for raspberrypi3-64 as well

recipes-kernel/linux-firmware/linux-firmware_%.bbappend
- raspbian-nf = "b518de45ced519e8f7a499f4778100173402ae43"
- raspbian-bluez = "ade2bae1aaaebede09abb8fb546f767a0e4c7804"
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
=> linux-firmware: Bump revisions

conf/machine/include/rpi-base.inc
This adds the gpio-key to the devicetree overlay list.
=> Extend devicetree overlays

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend, recipes-graphics/userland/userland_git.bb
These names are mapped to mesa equivalent rproviders
when using vc4 rdep should be on libegl1 which is then
mapped to libegl-mesa since thats what provides libegl1
when using mesa. The libegl is not a global name for this
library
Fixes
ERROR: userland-20181120-r0 do_package_qa: QA Issue: /usr/lib/libWFC.so
contained in package userland requires libEGL.so.1, but no providers
found in RDEPENDS_userland? [file-rdeps]
=> userland: rprovide debiannamed libraries

classes/sdcard_image-rpi.bbclass, docs/extra-build-config.md
SDIMG_COMPRESSION is not used too much, and it has limitations for
multi-threaded compression process. Instead, meta/classes/image_types.bbclass
does the trick in a generic and supported way, thus it was suggested
to remove SDIMG_COMPRESSION variable and related codepaths altogether
to avoid confusion in the future. IMAGE_FSTYPES variable should be used
instead.
Signed-off-by: Iurii Lunev <koolkhel@mail.ru>
I removed SDIMG_COMPRESSION definition and usage so no references to that variable exist anymore.
By removing :-) See the earlier PR here for reasoning: https://github.com/agherzan/meta-raspberrypi/pull/210
=> Remove support of the deprecated SDIMG_COMPRESSION variable

conf/machine/include/rpi-base.inc, docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-config_git.bb, recipes-core/udev/udev-rules-rpi.bb, recipes-core/udev/udev-rules-rpi/can.rules
In order to make Pican 2 work, we :
- add mcp2515.dto to the overlay list
- add a variable to enable it in local.conf
- create a udev rule to mount interface
http://skpang.co.uk/catalog/pican2-canbus-board-for-raspberry-pi-23-p-1475.html
Signed-off-by: Fabien Lahoudere <fabien.lahoudere@collabora.com>
=> CAN: Add Pican2 support

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
- Drop enabling linuxfb, now we can get eglfs going
- Enable kms and gbm feature when using vc4graphics driver
- No need to set OE_QTBASE_EGLFS_DEVICE_INTEGRATION when using vc4graphics
=> qtbase: Get eglfs/kms working with vc4graphics

docs/contributing.md
As briefly discussed in PR #335, here are some improvements to the contributing section of the documentation to clarify patch formatting.
* Rephrased some paragraphs
* Better organised the section itself
* Added guideline and formatting examples for commit log messages
Let me know what do you think and suggestions.
=> docs: improve the contributing section

recipes-bsp/common/firmware.inc, recipes-kernel/linux/linux-raspberrypi_4.14.bb
Fixes https://github.com/raspberrypi/firmware/issues/1051
=> Update firmware and kernel

recipes-graphics/userland/userland_git.bb
This avoids a missing rdep errors seen sometimes when switching
compilers or graphic driver providers
ERROR: userland-20181120-r0 do_package_qa: QA Issue: /usr/lib/libWFC.so contained in package userland requires li bEGL.so.1, but no providers found in RDEPENDS_userland? [file-rdeps]
=> userland: Use original name libegl-mesa in rdeps

recipes-kernel/linux/linux-raspberrypi-rt_4.14.bb
select the rt kernel by adding in local.conf:
PREFERRED_PROVIDER_virtual/kernel = "linux-raspberrypi-rt"
Signed-off-by: Phong Tran <tranmanphong@gmail.com>
append a new recipe for selection the linux rt  
kernel source here: https://github.com/raspberrypi/linux/tree/rpi-4.14.y-rt
- Build and boot with MACHINE = "raspberrypi3-64" (core-image-base)
=> linux-raspberrypi: add linux-raspberrypi-rt 4.14

conf/machine/raspberrypi3-64.conf
rpi3 is based on cortex-a53 implementation which is armv8+crc+simd
now that OE-Core has the appropriate tunes, switch to using the new
tune file, bonus, is that chromium will be more optimized now
=> raspberrypi3-64.conf: Use more appropriate tune

recipes-devtools/wiringpi/files/0001-Add-initial-cross-compile-support.patch
This gives the variable `DYN_VERS_MAJ` in `devLib/Makefile` and `wiringPi/Makefile` a value by splitting on the dot in `VERSION`.
=> Fixes #362

recipes-devtools/raspi-gpio/raspi-gpio_git.bb
Added handy tool which can be used to trace down how gpio on RPI are
configured + add possibility to update.
Signed-off-by: Marek Belisko <marek.belisko@open-nandra.com>
=> devtools: Added raspi-gpio

recipes-kernel/bluez-firmware-rpidistro/bluez-firmware-rpidistro_git.bb
Latest bluez-firmware release updates BCM4345C0.hcd to
003.001.025.0156.0280, restoring LE scan capability.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
=> bluez-firmware-rpidistro: update bluez-firmware

recipes-bsp/bootfiles/rpi-config_git.bb
Enabled escape sequence because on some systems bash doesn't escape sequences by default.
=> Fixes: #169

classes/sdcard_image-rpi.bbclass
Closes: #382
Added -F32 to the mkfs.vfat step
=> sdcard_image-rpi: Format boot partition as FAT32

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend, recipes-graphics/cairo/cairo_%.bbappend, recipes-graphics/mesa/mesa-gl_%.bbappend, recipes-kernel/linux/linux-raspberrypi_4.19.bb
Newer changes in OE-Core means we need to do some adjustments to get userland graphics going again. This patchset addresses that. Please note that it will also need
http://lists.openembedded.org/pipermail/openembedded-core/2019-February/279490.html
=> Build X11/eglfs images with userland graphics

recipes-kernel/linux/linux-raspberrypi_4.19.bb
The rpi-4.19.y branch has been rebased and the commit specified for
4.19.30 no longer exists upstream.
Signed-off-by: Peter A. Bigot <pab@pabigot.com>
=> linux_raspberrypi_4.19: Update to 4.19.32

recipes-kernel/linux/linux-raspberrypi_4.19.bb
* The branch rpi-4.19.y (and rpi-4.18.y) was recently force pushed and
current d65a0f76d3adcf86a6f5c614c68edb3aeb3b8590 nor previous
3c468fc8191d276e3e9efd976a0ff71271f3fc51 aren't included in any
branch, from my local checkout update:
e24b1f6c0c79..5f4b16e4a8d6 rpi-4.14.y -> up/rpi-4.14.y
e54efc381a97..22bb67b8e2e8 rpi-4.14.y-rt -> up/rpi-4.14.y-rt
3a1a31d70660...d58c595b013f rpi-4.18.y -> up/rpi-4.18.y (forced update)
48dfbb408fdd...ab8652c03fa0 rpi-4.19.y -> up/rpi-4.19.y (forced update)
[new branch] rpi-4.20.y -> up/rpi-4.20.y
[new branch] rpi-5.0.y -> up/rpi-5.0.y
=> linux_raspberrypi_4.19: Update to 4.19.34

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
As per [Qt 5.12.2 commit update](https://github.com/meta-qt5/meta-qt5/commit/28d4bfdf74ba9d66ad749fc7208ca8dc147a3927), xkbcommon-evdev PACKAGECONFIG option has been renamed to xkbcommon.
This commit fixes BitBake QA:
WARNING: qtbase-5.12.2+gitAUTOINC+856fb1ab44-r0 do_configure: QA Issue: qtbase: invalid PACKAGECONFIG: xkbcommon-evdev [invalid-packageconfig]
**Note for maintainers**
I do not think those rpi appends are necessary anymore. The very same configuration is now automatically enforced in meta-qt5 by default. (Look above).
Before merging, I would like to discuss whether the appends are still required.
Thanks
=> qtbase_%.bbappend: update PACKAGECONFIG name for xkbcommon

classes/sdcard_image-rpi.bbclass
FATPAYLOAD has been put into double quotation marks. Otherwise, when its value is compound  (like "filename_1   filename_2   filename_3") it generates parsing error.
Signed-off-by: Nataliya Korovkina <malus.brandywine@gmail.com>
=> meta-raspberrypi: sdcard_image-rpi, Minor bug in use of FATPAYLOAD variable

recipes-multimedia/omxplayer/omxplayer/0007-Remove-Makefile-hardcoded-arch-tune.patch, recipes-multimedia/omxplayer/omxplayer_git.bb
Fixes: #428
Signed-off-by: Martin Schuessler <tossprobe@gmail.com>
Removed the hardcoded arch and tune settings from Makefile 
Patching the Makefile
=> omxplayer: remove hardcoded tune and arch from Makefile

recipes-graphics/vc-graphics/vc-graphics.inc
The current firmware archive doesn't contain a sbin directory anymore, so it failed for me when trying to install `vcdbg`. I fixed this.
Just removed the lines affecting sbin.
=> Remove sbin directory that's not part of the firmware anymore

recipes-kernel/linux/linux-raspberrypi_4.14.bb
Backport the upgrade to 4.12.112 from warrior to fix building lttng-modules-2.10.9 recently backported to oe-core thud.
Without this upgrade lttng-modules build fails with:
lttng-modules/2.10.9-r0/lttng-modules-2.10.9/probes/../blacklist/kprobes.h:19:4: error: #error "Your kernel is known to have buggy optimized kprobes implementation. Fixed by commit 0ac569bf6a7983c0c5747d6df8db9dc05bc92b6c \"ARM: 8834/1: Fix: kprobes: optimized kprobes illegal instruction\" in Linux. Disable CONFIG_OPTPROBES or upgrade your kernel."
\#  error "Your kernel is known to have buggy optimized kprobes implementation. Fixed by commit 0ac569bf6a7983c0c5747d6df8db9dc05bc92b6c \"ARM: 8834/1: Fix: kprobes: optimized kprobes illegal instruction\" in Linux. Disable CONFIG_OPTPROBES or upgrade your kernel."
=> linux-raspberrypi: Update 4.14.y kernel

recipes-kernel/linux/linux-raspberrypi_4.19.bb
Fixes vc4 graphics issues seen with 4.19.56
Add -@ to device tree flags so we can debug/dump the
dtb with symbols, helps in debugging the overlays
=> linux-raspberrypi: Upgrade to 4.19.57

recipes-kernel/linux/linux-raspberrypi.inc
We already do this for rpi3-64 and we will need it for rpi4-64 as well.
See 6c4de0b5fe44b8e661f1391ee8540a7f04d75315 for more details.
CC @diegosueiro
=> linux-raspberrypi: Build dtbs with dtbs make target for rpi4-64

recipes-connectivity/bluez5/bluez5_%.bbappend
Just a minor PR to fix a typo in bluez5_%.bbappend file.
Note : This typo is also in `warrior` branch
=> Fixed typo (RC_URI -> SRC_URI) in bluez5_%.bbappend

conf/machine/include/rpi-base.inc
gstreamer1.0-plugins-bad : Packaging gstreamer
plugins.
Signed-off-by: Riyaz <Riyaz.l@ltts.com>
=> meta-raspberrypi: Enabling vc4graphics machine feature.

conf/machine/raspberrypi4-64.conf
The PCI controller on the Raspberry Pi 4 acts as a DMA controller and can
only address the first 3Gb[1] of the memory space. On 32bit this was
addressed by implementing bouncing buffers[2] but this currently has no
support for arm64. In order to have working USB, as a workaround, we
limit the ram to 3G.
Fixes #446
[1] https://github.com/raspberrypi/linux/issues/3093
[2] https://github.com/raspberrypi/linux/blob/rpi-4.19.y/drivers/pci/controller/pcie-brcmstb-bounce.c
=> raspberrypi4-64.conf: Limit RAM to 3G

conf/machine/raspberrypi4-64.conf
The PCI controller on the Raspberry Pi 4 acts as a DMA controller and can
only address the first 3Gb[1] of the memory space. On 32bit this was
addressed by implementing bouncing buffers[2] but this currently has no
support for arm64. In order to have working USB, as a workaround, we
limit the ram to 3G.
Fixes #446
[1] https://github.com/raspberrypi/linux/issues/3093
[2] https://github.com/raspberrypi/linux/blob/rpi-4.19.y/drivers/pci/controller/pcie-brcmstb-bounce.c
=> [warrior backport] raspberrypi4-64.conf: Limit RAM to 3G

conf/layer.conf, dynamic-layers/networking-layer/recipes-support/drbd/drbd_%.bbappend, recipes-graphics/userland/files/0001-Allow-applications-to-set-next-resource-handle.patch, recipes-graphics/userland/files/0002-wayland-Add-support-for-the-Wayland-winsys.patch, recipes-graphics/userland/files/0003-wayland-Add-Wayland-example.patch, recipes-graphics/userland/files/0004-wayland-egl-Add-bcm_host-to-dependencies.patch, recipes-graphics/userland/files/0005-interface-remove-faulty-assert-to-make-weston-happy-.patch, recipes-graphics/userland/files/0006-zero-out-wl-buffers-in-egl_surface_free.patch, recipes-graphics/userland/files/0007-initialize-front-back-wayland-buffers.patch, recipes-graphics/userland/files/0008-Remove-RPC_FLUSH.patch, recipes-graphics/userland/files/0009-fix-cmake-dependency-race.patch, recipes-graphics/userland/files/0010-Fix-for-framerate-with-nested-composition.patch, recipes-graphics/userland/files/0011-build-shared-library-for-vchostif.patch, recipes-graphics/userland/files/0012-implement-buffer-wrapping-interface-for-dispmanx.patch, recipes-graphics/userland/files/0013-Implement-triple-buffering-for-wayland.patch, recipes-graphics/userland/files/0014-GLES2-gl2ext.h-Define-GL_R8_EXT-and-GL_RG8_EXT.patch, recipes-graphics/userland/files/0015-EGL-glplatform.h-define-EGL_CAST.patch, recipes-graphics/userland/files/0016-Allow-multiple-wayland-compositor-state-data-per-pro.patch, recipes-graphics/userland/files/0017-khronos-backport-typedef-for-EGL_EXT_image_dma_buf_i.patch, recipes-graphics/userland/files/0018-Add-EGL_IMG_context_priority-related-defines.patch, recipes-graphics/userland/files/0019-libfdt-Undefine-__wordsize-if-already-defined.patch, recipes-graphics/userland/userland_git.bb, recipes-sato/webkitgtk/webkitgtk_%.bbappend
Fix build with glibc 2.30
Forward patches to 20190724 release
=> userland: Upgrade to latest

recipes-bsp/u-boot/u-boot-2019.01/0001-Fix-compilation-error-if-CONFIG_USB-is-disabled.patch, recipes-bsp/u-boot/u-boot_2019.01.bbappend
Raspberry Pi 4 doesn't have a working USB driver in u-boot. This makes
the defconfig not to enable the relevant config case which breaks the
build with:
error: expected '}' before
'BOOT_TARGET_DEVICES_references_USB_without_CONFIG_CMD_USB'
This was fixed in upstream and we backport the relevant commit.
Signed-off-by: Andrei Gherzan <andrei@balena.io>
=> [warrior] u-boot: Backport patch to fix u-boot compilation without USB config

recipes-core/packagegroups/packagegroup-rpi-test.bb
this should bring in crda if needed
Fixes issue #456
=> packagegroup-rpi-test: Depend on wireless-regdb instead of crda

recipes-graphics/xorg-xserver/xserver-xorg_%.bbappend
There is no need to override complete packageconfig but just the openGL
part, this ensures that any common change in oe-core reflects for rpi as
well and does not cause the packageconfigs to go stale
=> xorg-xserver: Adapt bbappend to latest OE-core

recipes-multimedia/omxplayer/omxplayer/0004-Add-FFMPEG_EXTRA_CFLAGS-and-FFMPEG_EXTRA_LDFLAGS.patch, recipes-multimedia/omxplayer/omxplayer/0007-Remove-Makefile-hardcoded-arch-tune.patch, recipes-multimedia/omxplayer/omxplayer_git.bb
Updated SRCREV to `f543a0d0e707ab56415f17b0ca6d397394ee8b63` to fix playback errors on RPi 4 (https://github.com/popcornmix/omxplayer/issues/733).
=> omxplayer: Bump revision

recipes-kernel/linux/linux-raspberrypi_4.14.bb
Kernel 4.19.y and above was patched to rename the Raspberry Pi Zero W dts file. Unfortunately, this modification was not propagated to previous versions of the kernel, especially on the 4.14.y series which is still supported in this layer.
This modification leads to kernel 4.14.y build failure because the correct .dts file is not found.
This patch backports the mainline series patch downstream on 4.14.y series.
I am also creating a pull request on rpi-4.14.y so that this file can be deleted when the patch is accepted.
Signed-off-by: Francesco Giancane <francescogiancane8@gmail.com>
=> Update kernel 4.14 series recipe to 4.14.114

recipes-kernel/linux/linux-raspberrypi-rt_4.14.bb
Update linux kernel 4.14 series recipe for building with latest -rt
branch.
This fixes #474.
=> linux-raspberrypi-rt: update to latest commit for 4.14 series

dynamic-layers/openembedded-layer/recipes-kernel/linux/bpftool.bbappend, recipes-graphics/mesa/mesa_%.bbappend
This enables new v3d driver which needs kmsro as dependency
This will start working fully after oe-core change [1] is merged
[1] http://lists.openembedded.org/pipermail/openembedded-core/2019-August/285763.html
=> mesa: Enable vc4, v3d, kmsro gallium drivers

recipes-bsp/common/raspberrypi-firmware.inc
* with 4.19.66 kernel the vc4-fkms no longer works, because it doesn't
get any usable modes from firmware
* this behavior was introduced probably in one of following changes:
https://github.com/raspberrypi/firmware/commit/38e81f25e639d19fc0ce6e67fd39998c340a15d5
https://github.com/raspberrypi/linux/pull/3082
https://github.com/raspberrypi/linux/pull/3110
https://github.com/raspberrypi/firmware/commit/66bafab005569e3eb92ec54cd3efeee3da338738
* without this fix:
root@rpijama:~# cat /proc/device-tree/soc/firmwarekms@7e600000/status
okay
root@rpijama:~# modeprint vc4
Starting test
Resources
count_connectors : 1
count_encoders   : 1
count_crtcs      : 1
count_fbs        : 0
Connector: HDMI-A-1
id             : 51
encoder id     : 0
conn           : connected
size           : 0x0 (mm) …
=> raspberrypi-firmware: upgrade to latest to fix vc4-fkms

docs/extra-build-config.md
This makes it clear that ENABLE_UART can be used both for the **RPi 0W** or 3.
Just updated the "Enable UART" section of `docs/extra-build-config.md`
=> add RPi 0W to UART doc section

conf/machine/include/rpi-base.inc, conf/machine/raspberrypi3-64.conf, conf/machine/raspberrypi4-64.conf, conf/machine/raspberrypi4.conf, docs/extra-build-config.md
By default, each machine uses `vc4` for graphics. This will in turn sets mesa as provider for `gl` libraries. `DISABLE_VC4GRAPHICS` can be set to `1` to disable this behaviour falling back to using `userland`. Be aware that `userland` has not support for 64-bit arch. If you disable `vc4` on a 64-bit Raspberry Pi machine, expect build breakage.
=> Introduce DISABLE_VC4GRAPHICS

recipes-core/psplash/psplash_%.bbappend
Alternatives priority of psplash in poky is now 100,
so we need something higher (fixes #381).
Signed-off-by: Gianluigi Tiesi <sherpya@netfarm.it>
(cherry picked from commit 7059c374512f1c1c0df9ecab0703d11438bdf78b)
=> psplash: Raise alternatives priority to 200

classes/sdcard_image-rpi.bbclass, recipes-bsp/bootfiles/bcm2835-bootfiles.bb
Intuitively, bcm2835-bootfiles:do_deploy should depend on rpi-config:do_deploy.
This indirectly resolves a missing dep between rpi-config:do_deploy and
do_image_rpi_sdimg (on an image recipe inheriting from sdcard_image-rpi.bbclass).
This manifested as changes to rpi-config (e.g. setting or unsetting
ENABLE_* variables) not triggering a rebuild of the SD card image.
Signed-off-by: Chris Laplante <mostthingsweb@gmail.com>
=> bcm2835-bootfiles: tighten up dep on rpi-config

recipes-devtools/raspi-gpio/raspi-gpio_git.bb
This includes the following changes:
2eaa8b8 Initialise hwbase so that access without /dev/gpiomem works again
f36777c Whitespace tidyup (and re-ran astyle). No functional changes.
80fa7d0 Add support for 2711
bf7f4c8 Reformat with astyle (cosmetic change)
aa55bbd Autoreconf for Buster
5e453d0 raspi-gpio: Fix handling of "funcs" mode
=> raspi-gpio: bump to revision 2eaa8b8

classes/sdcard_image-rpi.bbclass
Use the IMAGE_NAME_SUFFIX variable to build the SDIMG name. Some layers,
notably meta-mender, change the IMAGE_NAME_SUFFIX variable to something
other that ".rootfs", causing build failures.
Signed-off-by: Francois Retief <fgretief@gmail.com>
=> sdcard_image-rpi.bbclass: Use IMAGE_NAME_SUFFIX variable in SDIMG

recipes-connectivity/pi-bluetooth/pi-bluetooth_0.1.12.bb
Add udev-rules-rpi as a runtime dependency. It brings udev rules
for creating /dev/serial1. This way hciuart.service, provided by
pi-bluetooth, will be successfully started because it depends
on dev-serial1.device. As a result the Bluetooth module will
be properly attached via UART HCI to BlueZ stack.
=> pi-bluetooth: Runtime depends on udev-rules-rpi

recipes-kernel/linux/linux-raspberrypi.inc
#533 
Can I hope to also see this in the Warrior branch?
=> linux-raspberrypi.inc: no longer set CONFIG_LOCALVERSION to empty string

recipes-kernel/linux/linux-raspberrypi-rt_4.19.bb
This version includes a fix for the USB part.
Fixes:
[    2.988098] CPU: 3 PID: 79 Comm: irq/56-dwc_otg_ Not tainted 4.19.71-rt24 #1
[    2.988102] Hardware name: BCM2835
[    2.988134] [<801120a8>] (unwind_backtrace) from [<8010d260>] (show_stack+0x20/0x24)
[    2.988151] [<8010d260>] (show_stack) from [<8085340c>] (dump_stack+0xbc/0x100)
[    2.988167] [<8085340c>] (dump_stack) from [<80121160>] (__warn.part.0+0xcc/0xe8)
[    2.988182] [<80121160>] (__warn.part.0) from [<80121314>] (warn_slowpath_null+0x54/0x5c)
[    2.988197] [<80121314>] (warn_slowpath_null) from [<8014f120>] (migrate_disable+0x220/0x
=> linux-raspberrypi-rt: bump to revision e2e9cec

recipes-kernel/linux/linux-raspberrypi-rt_4.19.bb
This version includes a fix for the USB part.
Fixes:
[    2.988098] CPU: 3 PID: 79 Comm: irq/56-dwc_otg_ Not tainted 4.19.71-rt24 #1
[    2.988102] Hardware name: BCM2835
[    2.988134] [<801120a8>] (unwind_backtrace) from [<8010d260>] (show_stack+0x20/0x24)
[    2.988151] [<8010d260>] (show_stack) from [<8085340c>] (dump_stack+0xbc/0x100)
[    2.988167] [<8085340c>] (dump_stack) from [<80121160>] (__warn.part.0+0xcc/0xe8)
[    2.988182] [<80121160>] (__warn.part.0) from [<80121314>] (warn_slowpath_null+0x54/0x5c)
[    2.988197] [<80121314>] (warn_slowpath_null) from [<8014f120>] (migrate_disable+0x220/0x
(cherry picked from commit d059288fa09ce072eade66efcb574db7831d3493)
=> linux-raspberrypi-rt: bump to revision e2e9cec (zeus backport)

recipes-devtools/python/rpi-gpio/0001-Remove-nested-functions.patch, recipes-devtools/python/rpi-gpio_0.7.0.bb
Also:
- update the HOMEPAGE location
- refresh patch
- use 'distutils3' to support python3 -> python2 is now deprecated
=> rpi-gpio: bump to version 0.7.0

recipes-devtools/raspi-gpio/raspi-gpio_git.bb
This includes the following changes:
4edfde1 Update raw output to show pull registers on 2711
=> raspi-gpio: bump to revision 4edfde1

conf/machine/raspberrypi4-64.conf, conf/machine/raspberrypi4.conf
This pulls in the pciutils package (including `lspci`) via packagegroup-base.
=> conf/machine: add pci to MACHINE_FEATURES for Pi4

recipes-connectivity/pi-bluetooth/pi-bluetooth_0.1.12.bb
After bc7b654feecceee46bb11800b69994640d03b0ad, we made this package
depend on a package that is not allarch while this is. Let's drop it for
this package as well to avoid these sstate signature issues.
=> pi-bluetooth: Fix signature failures

conf/machine/include/rpi-base.inc, docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-config_git.bb
Add support for the Adafruit PiTFT Plus 320x240 2.8" TFT with
Capacitive Touchscreen, using the same patterns used for the other
versions of the PiTFT screens.
Signed-off-by: Erik Botö <erik.boto@gmail.com>
=> Add support for PiTFT 2.8" with capacitive touch

README.md, kas-poky-rpi.yml
The kas tool provides an easy mechanism to setup bitbake based projects.
As explained in [1] the key features provided by kas are:
- clone and checkout bitbake layers
- create default bitbake settings (machine, arch, ...)
- launch minimal build environment, reducing risk of host contamination
- initiate bitbake build process
So, let's create a minimal example in this layer to build an image with a
small effort. This seems interesting for new users of the meta-raspberrypi.
For example:
$: sudo pip3 install kas
$: mkdir rpi
$: cd rpi
$: git clone https://github.com/agherzan/meta-raspberrypi.git
$: kas build meta-raspberrypi/kas-rpi.yml
and that's all !
To adjust the construction with specific options (I2C, SPI, ...), simply add
a section as follows:
local_conf_header:
rpi-specific: | …
=> [RFC] kas-poky-rpi: add kas file

recipes-multimedia/omxplayer/omxplayer_git.bb
Without this it might complain that libomxil isn't available when userland is preferred virtual/libomxil provider.
=> omxplayer: respect virtual/libomxil

recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_%.bbappend
OE-core now uses meson to build gstreamer
=> gstreamer1.0-plugins-base: Adjust for meson conversion

recipes-kernel/linux/files/0001-perf-Make-perf-able-to-build-with-latest-libbfd.patch, recipes-kernel/linux/linux-raspberrypi_4.19.bb
* fixes:
|   LINK     /OE/build/oe-core/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/perf/1.0-r9/perf-1.0/perf
| /OE/build/oe-core/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/perf/1.0-r9/perf-1.0/libperf.a(libperf-in.o):srcline.c:function find_address_in_section: error: undefined reference to 'bfd_get_section_flags'
| /OE/build/oe-core/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/perf/1.0-r9/perf-1.0/libperf.a(libperf-in.o):srcline.c:function find_address_in_section: error: undefined reference to 'bfd_get_section_vma'
| /OE/build/oe-core/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/perf/1.0-r9/perf-1.0/libperf.a(libperf-in.o):srcline.c:function find_address_in_section: error: undefined reference to 'bfd_get_section_size'
| collect2: error: ld returned 1 exit status
| make[2]: *** …
=> linux-raspberrypi: fix perf build with latest binutils

recipes-bsp/common/raspberrypi-firmware.inc, recipes-kernel/linux/linux-raspberrypi_4.19.bb
Tested on rpi3:
```
root@raspberrypi3:~# uname -a
Linux raspberrypi3 4.19.108-v7 #1 SMP Fri Mar 6 17:51:28 UTC 2020 armv7l GNU/Linux
```
=> linux-raspberry: bump to Linux version 4.19.108

recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_%.bbappend
When we tried to build the meta-multimedia-image, we faced the
compilation issue with faad component.
Since faad component has commercial license, we could not able
to build with multimedia image. So we have modified the faad
component to be included when commercial licenese is supported.
Signed-off-by: Madhavan Krishnan <madhavan.krishnan@linaro.org>
=> gstreamer: Fix the compilation issue in meta multimedia image

recipes-graphics/mesa/files/0001-dri2-query-dma-buf-modifiers.patch
Fixes
ERROR: mesa-2_20.0.1-r0 do_patch: Fuzz detected:
Applying patch 0001-dri2-query-dma-buf-modifiers.patch
patching file src/gallium/state_trackers/dri/dri2.c
Hunk #1 succeeded at 1366 with fuzz 1 (offset -2 lines).
=> mesa: Fix patch fuzz

conf/layer.conf, lib/oeqa/runtime/cases/parselogs_rpi.py
These errors are harmless on rpi3/rpi4 [1]
[1] https://github.com/raspberrypi/linux/issues/3195
=> oeqa: Add rpi specific kernel dmesg parser

conf/machine/include/rpi-base.inc
Closes #602.
These overlays have been added in https://github.com/raspberrypi/firmware/commit/910297737865b68d64f8419a92327a03ac04b72d.
I will also create a PR for the `zeus` branch.
=> rpi-base.conf: add disable-bt.dtbo and miniuart-bt.dtbo overlays.

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
This avoids adding unnessary dependency at runtime on userland graphics
package when vc4 driver is used
=> qtbase: Append userland to rdeps iff vc4graphics is not enabled

docs/extra-build-config.md
Add instructions how to auto-load I2C kernel modules with
KERNEL_MODULE_AUTOLOAD when I2C is enabled.
Updated the documentation and added instructions how to auto-load I2C kernel modules when I2C is enabled.
By default, even when I2C is enabled with `ENABLE_I2C="1"`, related kernel modules `i2c-dev` and `i2c-bcm2708` are not automatically loaded. In many cases developers prefer to have they automatically loaded and this can be achieved with the following additional settings:
```
KERNEL_MODULE_AUTOLOAD_rpi += "i2c-dev i2c-bcm2708"
```
I have added the example to the documentation. Although I am aware about this detail, I often forget to set `KERNEL_MODULE_AUTOLOAD`. Probably others are having the same …
=> docs/extra-build-config.md: Auto-load I2C modules

classes/sdcard_image-rpi.bbclass, conf/machine/include/rpi-default-providers.inc, recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr.bb, recipes-bsp/u-boot/u-boot_%.bbappend
Add u-boot-default-script to the PROVIDES variable to make easier to
replace boot script in another layer just by changing
PREFERRED_PROVIDER_u-boot-default-script variable. Set rpi-u-boot-scr as
the default provider for meta-raspberrypi.
Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>
=> rpi-u-boot-scr: Set u-boot-default-script as provider

conf/machine/include/rpi-base.inc, recipes-kernel/linux/linux-raspberrypi_5.4.bb, recipes-kernel/linux/linux-raspberrypi_5.4.inc
This is next LTS that linux-raspberrypi is going to support. see [this](https://github.com/raspberrypi/linux/issues/3525)
=> Add 5.4 kernel recipe

conf/machine/raspberrypi3-64.conf, conf/machine/raspberrypi3.conf
This seems to be required to have a functional DSI display.
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>
Troubleshooting of blank Xorg display using the Pi Foundation display.
After changing this, core-image-sato works on both HDMI and the DSI display.
=> RFC: raspberrypi3: Switch to vc4-fkms-v3d.

conf/machine/include/rpi-base.inc
Add kernel modules i2c-dev and i2c-bcm2708 to variable
MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS if ENABLE_I2C is set to 1.
This affects images based on packagegroup-core-boot, including
the core-image-minimal image.
The patch ensures that kernel modules` i2c-dev` and `i2c-bcm2708` are included in `core-image-minimal` if ENABLE_I2C is set to 1. This fix is for all images based on `packagegroup-core-boot`, including the `core-image-minimal` image which otherwise doesn't include`kernel-modules` because they are set in variable `MACHINE_EXTRA_RRECOMMENDS` which does **not** have effect for `core-image-minimal`. The patch improves the developer experience while working on `core-image-minimal` with I2C support.
I …
=> rpi-base.inc: Include modules if I2C is enaled

recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
Adjust PV to reflect the release and make it a bit meaningful
=> linux-firmware-rpidistro: Upgrade to 20190114-1+rpt6

recipes-core/psplash/psplash_%.bbappend
This simply causes build warnings about priority of two packages being
same, but infact this is redundant, therefore remove setting ALTERNATIVE_PRIORITY
for psplash-raspberrypi
=> psplash: Do not define ALTERNATIVE_PRIORITY for non-existing provider

README.md
Fixes incorrect Quick Start documentation, which previously suggested to dd an sdimg to the SD card rather than using bmaptool to copy the .wic.bz2 file. See #637.
I have left in the tip about using xzcat if an .xz is used, I can fix this up if this advice is also no longer valid.
=> docs: Correct Quick Start instructions to show the new .wic.bz2 extension

conf/machine/include/rpi-base.inc
Add device tree binary overlays gpio-ir-tx and gpio-ir-tx to
support peripherals for sending and receiving infrared signals.
Included gpio-ir-tx and gpio-ir-tx dtbo which are required for peripherals for sending and receiving infrared signals (for example using LIRC).
By adding gpio-ir-tx and gpio-ir-tx dtbo to variable `RPI_KERNEL_DEVICETREE_OVERLAYS`.
In the mean time I have submitted a patch to the upstream of meta-oe for upgrading LIRC to version 0.10.1. If it is approved I will carry on with LIRC bbappend file specific for Raspberry Pi.
Best regards, Leon
=> rpi-base.inc: Add infrared dtbo

conf/machine/include/rpi-base.inc, recipes-graphics/userland/userland_git.bb, recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_%.bbappend
Enabling vc4graphics support on morty branch
To bring vc4graphics enabled RPI image from morty branch, remaining changes to enable vc4graphics are notified and applied.
Userland required some more changes in EGL provider's changes between userland and mesa. This is notified and applied.
=> vc4 support on morty branch

recipes-connectivity/lirc/lirc/lirc-gpio-ir-0.10.patch, recipes-connectivity/lirc/lirc_%.bbappend
Apply Raspberry Pi specific fix for gpio-ir kernel module:
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=235256
Fix LIRC on Raspberry Pi with a patch that is known to work with gpio-ir kernel module as explained in the Raspberry Pi forums:
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=235256
With a `.bbappend` file for LIRC that applies the Raspberry Pi specific patch.
Best regards,
Leon
=> lirc_%.bbappend: Fix for gpio-ir

recipes-kernel/linux/files/0001-Revert-selftests-bpf-Skip-perf-hw-events-test-if-the.patch, recipes-kernel/linux/linux-raspberrypi_5.4.bb
Drop backported patches which are already in this release
Fixes Issue #658
=> linux-raspberrypi_5.4.bb: Upgrade to 5.4.47

recipes-core/packagegroups/packagegroup-rpi-test.bb
Replaces `wireless-regdb` with `wireless-regdb-static` provided by poky.
Fixes #639.
Signed-off-by: Jon Magnuson <jon.magnuson@gmail.com>
=> packagegroup-rpi-test: resolve `wireless-regdb` conflict

recipes-bsp/u-boot/u-boot/0001-dm-core-Move-ofdata_to_platdata-call-earlier.patch, recipes-bsp/u-boot/u-boot_%.bbappend
With stock u-bootv2020.01 which we use from poky CM3 module won't boot.
We need to apply this patch in order to have platform again working.
Add it only for cm3 to not break anythign else.
Signed-off-by: Marek Belisko <marek.belisko@open-nandra.com>
=> u-boot: Fix booting raspberrypi CM3 module

recipes-bsp/rpi-u-boot-scr/files/boot.cmd.in, recipes-bsp/u-boot/files/fw_env.config, recipes-bsp/u-boot/libubootenv_%.bbappend
Fix the following issue with `fw_printenv` while running an image with U-Boot:
```
root@raspberrypi3:~# fw_printenv 
Configuration file wrong or corrupted
```
To reproduce this issue add the following configurations to `local.conf`:
```
RPI_USE_U_BOOT = "1"
IMAGE_INSTALL_append = " u-boot-fw-utils"
```
The fix contains two parts (each in a separate git commit):
* Create `/boot/uboot.env` through `boot.cmd.in` from recipe `rpi-u-boot-scr`
* Add `fw_env.config` that uses `/boot/uboot.env` to run successfully `fw_printenv`
=> Fix fw_printenv when using U-Boot

recipes-kernel/linux/linux-raspberrypi_5.4.bb
Signed-off-by: Christopher Clark <christopher.w.clark@gmail.com>
Fixes the build since the upstream branch was force-pushed, so the
commit referenced in the SRCREV was no longer present in the branch.
Briefly boot-tested on a Raspberry Pi 4 with Xen via meta-virtualization.
=> linux-raspberrypi: bump to 5.4.50 since upstream was force-pushed

recipes-bsp/common/raspberrypi-firmware.inc, recipes-kernel/linux/linux-raspberrypi_5.4.bb
Tested on RPi3 with U-Boot:
```
U-Boot 2020.04 (Apr 13 2020 - 15:02:18 +0000)
DRAM:  948 MiB
RPI 3 Model B (0xa02082)
MMC:   mmc@7e202000: 0, sdhci@7e300000: 1
Loading Environment from FAT... OK
In:    serial
Out:   vidconsole
Err:   vidconsole
Net:   No ethernet found.
starting USB...
Bus usb@7e980000: scanning bus usb@7e980000 for devices... 3 USB Device(s) found
scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0 
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
263 bytes read in 1 ms (256.8 KiB/s)
5628880 bytes read in 235 ms (22.8 MiB/s)
Image Name:   Linux-5.4.51-v7
Image Type:   ARM Linux Kernel Image (uncompressed)
Data Size:    5628816 Bytes = 5.4 MiB
Load Address: 00008000
Entry Point: …
```
=> bump kernel

conf/machine/include/rpi-base.inc
As per the example in the bsp-guide, and the qemu and other machine
configs. Assists when running virtualized, where serial console
device can differ.
Signed-off-by: Christopher Clark <christopher.w.clark@gmail.com>
=> rpi-base: add SERIAL_CONSOLES_CHECK to default to SERIAL_CONSOLES

conf/machine/include/rpi-base.inc, docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-config_git.bb
The device tree only supports a single CAN interface. Dual-CAN boards like the PiCAN2 Duo are not currently supported.
An ENABLE_DUAL_CAN build configuration was added to enable both CAN interfaces.  Enabling this build configuration adds the second CAN interface to config.txt.  The mcp2515-can1 device tree blob overlay was added to RPI_KERNEL_DEVICETREE_OVERLAYS.  The docs were updated with information about the ENABLE_DUAL_CAN build configuration.
Signed-off-by: Colin McAllister colinmca242@gmail.com
=> Added dual CAN build configuration

conf/machine/include/rpi-base.inc
Apply this fix from master (#683) to dunfell. Tested on Raspberry Pi 4.
As per the example in the bsp-guide, and the qemu and other machine
configs. Assists when running virtualized, where serial console
device can differ.
Signed-off-by: Christopher Clark <christopher.w.clark@gmail.com>
=> dunfell: rpi-base: add SERIAL_CONSOLES_CHECK to default to SERIAL_CONSOLES

classes/sdcard_image-rpi.bbclass, conf/machine/include/rpi-base.inc, recipes-bsp/bootfiles/bootfiles.bb, recipes-bsp/bootfiles/rpi-config_git.bb, recipes-kernel/linux/linux-raspberrypi.inc
Generalized the bootfiles recipe and its output directory to remove the implication that they only support
the bcm2835 and not raspberry pi 4s bcm2711.
* Recipe is renamed to simply "bootfiles" from "bcm2835-bootfiles"
* Output directory and all references to it across all recipes renamed to "bootfiles" from "bcm2835-bootfiles"
=> bootfiles, rpi-config, rpi-base: generalize the bootfiles recipe

docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-config_git.bb
Add CAN_OSCILLATOR variable to make it possible to set frequency of the crystal oscillator used on the actual CAN board.
Current configuration (16MHz) is made for the PiCAN2 board, that uses 16MHz crystal. I use Waveshare RS485 CAN HAT that has 8MHz crystal soldered (although according to Waveshare there is also a 16MHz crystal version of the board).
=> rpi-config: Add CAN_OSCILLATOR variable to set mcp2515 crystal frequency

classes/sdcard_image-rpi.bbclass, docs/extra-build-config.md
Add DEPLOYPAYLOAD, similar to the existing FATPAYLOAD, to enable
adding files to the boot partition from the image deploy directory.
Files such as hypervisor binaries may not be present (and in fact
unwanted) within the root filesystem, so FATPAYLOAD is not sufficient.
DEPLOYPAYLOAD is implemented with support for file renaming from the
source file in the image deploy directory to the filename written into
the boot image. DEPLOYPAYLOAD is a space-separated list of entries for
additions, each of which is colon-separated:
>     <image deploy directory file>:<destination filename>
This is used for including Xen, which produces a machine-specific
file in the image deploy directory, with its expected filename: xen.
Files that are to be included from the image deploy directory will
be produced …
=> sdcard_image-rpi.bbclass: enable extensible inclusion into boot

classes/sdcard_image-rpi.bbclass
This includes a fix for https://github.com/agherzan/meta-raspberrypi/pull/684/files
CC @dozylynx
=> sdcard_image-rpi.bbclass: Fix when RPI_SDIMG_EXTRA_DEPENDS not defined

recipes-kernel/linux/linux-raspberrypi_5.4.bb
Needs some fixes from newer 5.4 kernel, e.g.:
1b940bbc5c55 Linux 5.4.56
df35e878d0a5 perf bench: Share some global variables to fix build with gcc 10
702d1b287fd2 perf env: Do not return pointers to local variables
73d2d6b421df perf tests bp_account: Make global variable static
to fix:
LINK     perf/1.0-r9/perf-1.0/perf
perf/1.0-r9/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/../../libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/10.1.0/ld: error: perf/1.0-r9/perf-1.0/plugins/libtraceevent-dynamic-list:2:15: invalid character
perf/1.0-r9/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/../../libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/10.1.0/ld: error: perf/1.0-r9/perf-1.0/plugins/libtraceevent-dynamic-list:2:15: syntax error, unexpected end of file, expecting ';' …
=> linux-raspberrypi-5.4: bump SRCREV to latest to fix perf build

README.md
These are android drivers, which help in running anbox on top of
raspberrypi machines
=> README: Mention Yoe distro in supported distro list

recipes-bsp/common/raspberrypi-firmware.inc, recipes-kernel/linux/linux-raspberrypi_5.4.bb
Tested on `rpi3`:
```
5896120 bytes read in 247 ms (22.8 MiB/s)
Saving Environment to FAT... OK
Image Name:   Linux-5.4.64-v7
Image Type:   ARM Linux Kernel Image (uncompressed)
Data Size:    5896056 Bytes = 5.6 MiB
Load Address: 00008000
Entry Point:  00008000
Verifying Checksum ... OK
Booting using the fdt blob at 0x2eff8e00
Loading Kernel Image
Using Device Tree in place at 2eff8e00, end 2f002f5b
Starting kernel ...
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.4.64-v7 (oe-user@oe-host) (gcc version 10.2.0 (GCC)) #1 SMP Fri Sep 11 12:57:30 UTC 2020
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
```
=> bump to Linux version 5.4.64

recipes-bsp/common/raspberrypi-firmware.inc, recipes-bsp/common/raspberrypi-tools.inc
* otherwise we end with big archives in downloads directory without clear
indication from where they came
* e.g. in one of my jenkins builds I've noticed:
```
-rw-rw-r-- 1 jenkins jenkins 178M Jun 30 15:45 downloads/23548e550a757d368d3d5220373fe829b5961c42.tar.gz
-rw-rw-r-- 1 jenkins jenkins 152M Sep  5  2019 downloads/7163480fff007dc98978899b556dcf06f8a462c8.tar.gz
-rw-rw-r-- 1 jenkins jenkins 179M Jul 23 01:34 downloads/7e74bcb4f9706f36f752d1c3d3164628ccf2aae5.tar.gz
-rw-rw-r-- 1 jenkins jenkins 178M Jun  5 12:34 downloads/7eff9f6774bb43bfd61e749a0b45ffddc98c2311.tar.gz
-rw-rw-r-- 1 jenkins jenkins 177M Apr 23 14:49 downloads/84523e0b9a9e78aa69fca1f1a8d75b2bdb5155fc.tar.gz
-rw-rw-r-- 1 jenkins jenkins 178M Jan 13  2020 downloads/9d6be5b07e81bdfb9c4b9a560e90fbc7477fdc6e.tar.gz
```
``` …
```
=> raspberrypi-{firmware,tools}: set downloadfilename

recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
* Update brcmfmac43455-sdio.bin to 7.45.206
* Add BCM43456 firmware
- brcm/brcmfmac43456-sdio.bin 7.84.17.1
- brcm/brcmfmac43456-sdio.clm_blob
- brcm/brcmfmac43456-sdio.txt
* Add compatibility links for direct firmware download to work properly
Fixes
brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43455-sdio.raspberrypi,4-model-b.txt failed with error -2
=> linux-firmware-rpidistro: Update to 20190114-1+rpt8

recipes-kernel/linux/linux-raspberrypi_5.4.bb, recipes-kernel/linux/linux-raspberrypi_5.4.inc
Fixes the following error:
ERROR. input file "cfg/virtio.scc" does not exist
Signed-off-by: Murat Kilivan <murat.kilivan@gmail.com>
=> linux-raspberrypi_5.4.bb: Add kernel-cache source

conf/layer.conf, dynamic-layers/multimedia-layer/recipes-multimedia/libcamera/libcamera.bbappend
libcamera middleware has supported many pipeline for frame capturing.
To enable the frame capture from raspberrypi board, added new
bbappend file, which will enable the raspberrypi pipeline while compiling.
Signed-off-by: Madhavan Krishnan <madhavan.krishnan@linaro.org>
=> libcamera: Added a recipe file for libcamera

recipes-devtools/python/python3-rtimu_git.bb
* see oe-core base.bbclass changes from:
https://lists.openembedded.org/g/openembedded-core/message/143159
https://lists.openembedded.org/g/openembedded-core/message/143161
=> python3-rtimu: don't use trailing slash in S

recipes-kernel/linux/linux-raspberrypi.inc
When multiple kernels are being built, not all of them can deploy the
same file.
This patch assumes the same command line arguments is used by all kernels.
Related to https://github.com/agherzan/meta-raspberrypi/pull/736
=> linux-raspberrypi: Only deploy cmdline.txt for the main kernel

recipes-kernel/linux/linux-raspberrypi.inc
When multiple kernels are being built, not all of them can deploy the same file. A use case for this is when Linux is being used as a bootloader to kexec a new kernel, and the initial one is configured differently to be much smaller in size.
This patch assumes the same command  line arguments is used by all kernels.
This is tested on the warrior branch so I PR it there. Once approved I will open a PR for master.
=> [warrior] linux-raspberrypi: Only deploy cmdline.txt for the main kernel

recipes-kernel/linux/linux-raspberrypi_5.4.bb
Tested on CM3, dunfell branch
```
Image Name:   Linux-5.4.72-v7
Image Type:   ARM Linux Kernel Image (uncompressed)
Data Size:    6062056 Bytes = 5.8 MiB
Load Address: 00008000
Entry Point:  00008000
Verifying Checksum ... OK
Booting using the fdt blob at 0x2eff9200
Loading Kernel Image
Using Device Tree in place at 2eff9200, end 2f002f3f
Starting kernel ...
```
I also verified that the bleeding tooth proof of concept does not work anymore https://github.com/google/security-research/security/advisories/GHSA-h637-c88j-47wq
=> linux-raspberrypi: bump to Linux version 5.4.72

recipes-graphics/userland/userland_git.bb
This warning is gcc specific and causes build failures when building
with clang, lets therefore remove it when build is using clang compiler
=> userland: Apply format-overflow warning patch for gcc alone

conf/layer.conf
* since
https://github.com/agherzan/meta-raspberrypi/commit/36c3c2e7ca09806da460328767565bbf872a6ad8
which renamed gstreamer1.0-omx_1.14%.bbappend to gstreamer1.0-omx_1.16%.bbappend it didn't
parse with zeus and older
* with zeus it parses OK, but I believe people who use meta-raspberrypi
from dunfell branch in zeus builds should rather ask for backports they
are missing in zeus branch
=> [dunfell] layer.conf: Remove older releases from LAYERSERIES_COMPAT

conf/layer.conf, dynamic-layers/multimedia-layer/recipes-multimedia/libcamera/libcamera.bbappend
This reverts commit a27f10b76cb1dbf089a3f0980e97f1931b090f17.
This was backported to dunfell together with many other changes in:
https://github.com/agherzan/meta-raspberrypi/pull/754
but 202002 version in dunfell fails with:
ERROR: QA Issue: libcamera: configure was passed unrecognised options: pipelines [unknown-configure-option]
202008 version in gatesgarth is fine, it was added in March:
https://git.linuxtv.org/libcamera.git/commit/meson_options.txt?id=ee7e2c93dfbf34b3500c895115c516e5e90d3e31
=> Revert "libcamera: Define packageconfig to enable rpi pipeline"

conf/machine/include/rpi-base.inc, docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-config_git.bb, recipes-kernel/linux/linux-raspberrypi.inc
Added imx219.dtbo file in the overlays, and added dtoverlay in
/boot/config.txt define based.
To enable SOny Raspberry pi camera imx219 sensor, need to set
the variable ENABLE_CAMERA_OVERLAY as 1.
In future, we can add any camera overlays here to support and
use them with libcamera.
Signed-off-by: Madhavan Krishnan <madhavan.krishnan@linaro.org>
=> libcamera: Enabled camera overlays define based

recipes-kernel/linux/linux-raspberrypi.inc
append operator and += when used together results in undefined behaviour
in bitbake
=> linux-raspberrypi: Do not use += with append

recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr.bb
Let's inherit kernel-arch and use ${UBOOT_ARCH} to replace the
hard-coded 'arm'.
Signed-off-by: Ming Liu <liu.ming50@gmail.com>
=> rpi-u-boot-scr: drop hard-coded 'arm'

recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_%.bbappend
This is not need any more to build with gstreamer 1.18
Signed-off-by: Jose Quaresma <quaresma.jose@gmail.com>
=> gstreamer1.0-plugins-base: drop custom cppflags

recipes-graphics/mesa/mesa-gl_%.bbappend
After mesa switched build system to meson, the logic to generate dri
related artifacts changed too, which means when no dri backend is
enabled then dri drivers and corresponding headers dont get generated
and hence we end up with missing pkgconfig files e.g. dri.pc which
usually will come from full mesa3d package, but in rpi when userland is
used we only build GL pieces of mesa.
This patch therefore enables swrast dri backend when using userland,
which gives us the needed header and .pc files to build packages like
Xorg server, since EGL driver will come from userland, the dri backend
would be unused and hence should not be effective at runtime.
Addresses issue report with https://github.com/agherzan/meta-raspberrypi/pull/773
Cc: Trevor Woerner …
=> mesa-gl: Enable swrast dri backend for rpi/userland

recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
I was building a yocto image for my raspberry pi zero w, but the wifi device was not created on boot. The issue which caused
this error was a missing link providing the brcmfmac43430 firmware (the driver was looking for brcmfmac43430-sdio.raspberrypi,model-zero-w.txt). Creating the link in /lib/firmware/brcm solved the issue.
I added the missing link creation to the responsible recipe.
=> Solving issue with not finding firmware for wlan on raspberrypi zero w

recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
Pi400 and CM4 use brcmfmac43456-sdio
Pi 400 and CM4 use the Broadcom BCM43456 WiFi chip instead of the BCM43455 in the Pi 4. This adds support.
Pull in the firmware files for brcmfmac43456-sdio from the RPi-Distro repo
=> Add brcmfmac43456-sdio for Pi400 and CM4

recipes-graphics/userland/userland_git.bb
Add a dummy entry for the "allapps" PACKAGECONFIG to avoid the QA
warning/error:
userland-20201027-r0 do_configure: QA Issue: userland: invalid PACKAGECONFIG: allapps [invalid-packageconfig]
Signed-off-by: Trevor Woerner <twoerner@gmail.com>
=> userland: dismiss invalid packageconfig

recipes-graphics/raspidmx/raspidmx_git.bb
Currently its only disabled when vc4graphics is in use but this recipe
actually needs userland and therefore can not be used for non-rpi
machines as well.
=> raspidmx: Disable for all non-rpi hosts

recipes-kernel/linux/linux-raspberrypi.inc
The functionality provided by this compile append is already present in
kernel-devicetree.bbclass since oe-core commit:
https://github.com/openembedded/openembedded-core/commit/74619de02774
The md5sums of the generated dtbs for raspberrypi3-64 and raspberrypi4-64 do
not change with this patch applied.
Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
=> linux-raspberry: Drop 64-bit specific do_compile_append()

conf/machine/include/rpi-base.inc, conf/machine/include/rpi-default-providers.inc
**Updated PR description:**
To allow other layers to easily provide a default kernel preference to use with the Raspberry Pi MACHINEs, switch to use the `??=` assignment operator for setting the default kernel and the device tree value in this layer.
This change is motivated by enabling Xen support in meta-virtualization to use the raspberrypi4-64 MACHINE definition from this layer with the Yocto Linux kernels.
Signed-off-by: Christopher Clark <christopher.w.clark@gmail.com>
**The previous PR description with the original commits that were proposed, and have since been replaced, was:**
_machine: add vendorkernel to MACHINE_FEATURES for default kernel pref_
Xen support in the meta-virtualization layer uses the raspberrypi4-64
MACHINE definition from this layer with the Yocto Linux kernels …
=> machine: use weak default for kernel and KERNEL_DEVICETREE settings

recipes-bsp/bootfiles/rpi-config_git.bb
@NobuoTsukamoto figured out that It seems like "start_x=1" needs to be earlier in the file to work properly on the Rapberry Pi 4 B.
Fixes: #670
=> rpi-config: Relocated "start_x=1" in config.txt

conf/machine/raspberrypi4-64.conf
Enable the use of RPI_EXTRA_CONFIG when targeting 64bit images on PI4.
Before this patch, use of RPI_EXTRA_CONFIG += in a local.conf would overwrite
the needed 'arm_64bit=1' defined in the core recipes.  The net result would be
a system that did not boot.
This patch fixes the assignment of 'arm_64bit=1' even if RPI_EXTRA_CONFIG
has been set elsewhere.
Signed-off-by: Your Name matthew@thespencers.me.uk
=> Enable use of 'RPI_EXTRA_CONFIG += ...' in local.conf

conf/machine/include/rpi-base.inc
Add overlays for justboom audio boards and reorder list to be in alphabetical order
Change-type: patch
Signed-off-by: Aaron Shaw <aaron@balena.io>
=> Add overlays for justboom and reorder

.gitignore, conf/machine/raspberrypi3-64.conf, conf/machine/raspberrypi4-64.conf, kas-poky-rpi.yml, recipes-kernel/linux/linux-raspberrypi_5.4.bb
* Update the kernel & yocto-kernel-cache to the latest upstream commits.
* Use unified u-boot config for 64-bit targets.
* We no longer need to force `arm_64bit=1` to boot Raspberry Pi 4 in 64-bit mode.
* Tidy up kas builds a little: Place cloned layers under a `layers` subdirectory and ignore this from git.
=> Kernel updates and minor config tweaks

recipes-kernel/linux/linux-raspberrypi.inc
'recipes-kernel/linux/linux-yocto.inc' already inherits 'kernel'.
This commit removes the superfluous one.
Resolves #797.
=> 'inherit kernel' is already required

recipes-kernel/linux/linux-raspberrypi-dev.bb, recipes-kernel/linux/linux-raspberrypi_5.4.bb
Currently, the do_compile log is cluttered with dtc warnings that should only
be printed when compiling with W="123":
...
/soc: node has a reg or ranges property, but no unit name
/soc/gpu: missing or empty reg/ranges property
/soc/firmware/gpio: missing or empty reg/ranges property
...
This happens because we pass dtc flags via KERNEL_EXTRA_ARGS directly on the
make command line, preventing scripts/Makefile.lib logic from appending flags
that silence dtc warnings (all assignments done from within a makefile, to a
variable specified on the command line, are ignored).
oe-core commit [1] introduced the dedicated KERNEL_DTC_FLAGS variable to pass
dtc flags via the environment. Use this variable to get rid of the do_compile
log noise.
The md5sums of the generated dtbs for raspberrypi3-64 and …
=> linux-raspberrypi: pass dtc flags via KERNEL_DTC_FLAGS

docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-config_git.bb
By default in case of CM4 IO board, the USB ports (header + built-in)
are disabled. In order to enable them the DWC2 mode needs to be set to
host.
Signed-off-by: Aurelian Zanoschi <aurelian17@gmail.com>
Added support for dwc2 host mode.
Modified the rpi-config recipe to support dwc2 host mode when ENABLE_DWC2_HOST option is enabled in conf.
=> rpi-config: Add support for CM4 host USB

docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-config_git.bb
By default in case of CM4 IO board, the USB ports (header + built-in)
are disabled. In order to enable them the DWC2 mode needs to be set to
host.
Added support for dwc2 host mode.
Modified the rpi-config recipe to support dwc2 host mode when ENABLE_DWC2_HOST option is enabled in conf.
=> [dunfell] rpi-config: Add support for CM4 host USB

conf/machine/include/rpi-base.inc, conf/machine/raspberrypi3-64.conf, conf/machine/raspberrypi4-64.conf
Add overlay to allow 64 bit usage with CM3
Change-type: patch
Signed-off-by: Aaron Shaw <aaron@balena.io>
Add CM3 overlay so you can use CM3 in 64 bit mode
Add overlay to conf file
=> Add overlay to allow 64 bit usage with CM3

recipes-bsp/bootfiles/rpi-cmdline.bb
With current recipe formatting CMDLINE variable contains
many unnecessary white spaces. This patch allow to drop
unnecessary spaces at the moment of writing them to
cmdline.txt. This will improve readability of cmdline.txt,
/proc/cmdline and dmesg output.
Signed-off-by: Bartłomiej Burdukiewicz <bartlomiej.burdukiewicz@gmail.com>
=> rpi-cmdline: remove unnecessary spaces from cmdline.txt

classes/sdcard_image-rpi.bbclass
* 5.10 kernel got a bit bigger especially for aarch64:
5.10:   22M     deploy/images/raspberrypi4-64/Image-raspberrypi4-64.bin
5.10:  7.0M     deploy/images/raspberrypi4/uImage-raspberrypi4.bin
5.4:    16M     deploy/images/raspberrypi4-64/Image-raspberrypi4-64.bin
5.4:   6.2M     deploy/images/raspberrypi4/uImage-raspberrypi4.bin
* and the space in fat boot partition was already tight:
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p1   40M   38M  1.7M  96% /
* increase the size to compensate for it, otherwise
do_image_rpi_sdimg now fails with:
Creating filesystem with Boot partition 40960 KiB and RootFS 1822720 KiB
0+0 records in
0+0 records out
0 bytes copied, 0.000100992 s, 0.0 kB/s
Model:  (file)
Disk foo.rootfs.rpi-sdimg: 1913MB
Sector size (logical/physical): …
=> sdcard_image-rpi.bbclass: increase default boot partition size from 40MiB to 48MiB

recipes-devtools/python/python3-adafruit-blinka_6.2.2.bb, recipes-devtools/python/python3-adafruit-circuitpython-busdevice_5.0.5.bb, recipes-devtools/python/python3-adafruit-circuitpython-motor_3.2.6.bb, recipes-devtools/python/python3-adafruit-circuitpython-motorkit_1.6.1.bb, recipes-devtools/python/python3-adafruit-circuitpython-pca9685_3.3.4.bb, recipes-devtools/python/python3-adafruit-circuitpython-register_1.9.4.bb, recipes-devtools/python/python3-adafruit-platformdetect_3.1.1.bb, recipes-devtools/python/python3-adafruit-pureio_1.1.8.bb
This makes it easy to use various Adafruit products, such as the DC & Stepper Motor Bonnet.
=> Add recipes for most of the Adafruit CircuitPython Python libraries

recipes-devtools/python/python3-adafruit-blinka_6.2.2.bb
https://github.com/agherzan/meta-raspberrypi/pull/815
introduced python3-adafruit-blinka and this recipe has added rdep on rpi-gpio,
however rpi-gpio is rpi specific package, and therefore should only be added
when building rpi based platforms, this makes the layer work in a
multi-bsp setup work
=> python3-adafruit-blinka: Make rpi-gpio dependency conditional

recipes-devtools/python/python3-adafruit-blinka_6.2.2.bb
It has prebuilt binary libgpiod_pulsein for rpi machines and these binary is 32bit
therefore we can not include it for 64bit machines even if they are rpi
based unless they have multilib enabled.
This patch makes it visible only on rpi-32bit
Fixes QA errors like
ERROR: QA Issue: Architecture did not match (ARM, expected AArch64) in /usr/lib/python3.9/site-packages/adafruit_blinka/microcontroller/bcm283x/pulseio/.debug/libgpiod_pulsein [arch]
=> python3-adafruit-blinka: Make it available only for 32bit rpi machines

conf/machine/include/rpi-base.inc
In theory, this would allow one to use the official 7-inch touchscreen
in combination with the (non-firmware) kms driver by adding the
following lines to config.txt:
ignore_lcd=1
dtoverlay=vc4-kms-v3d
dtoverlay=vc4-kms-dsi-7inch
Signed-off-by: Mike Looijmans <mike.looijmans@topic.nl>
=> Add overlay "vc4-kms-dsi-7inch.dtbo"

classes/sdcard_image-rpi.bbclass
* raspberrypi4-64 is 15 characters and with dosfstools-4.2 it breaks rootfs.rpi-sdimg with:
mkfs.vfat: Label can be no longer than 11 characters
mkfs.fat 4.2 (2021-01-31)
* introduced in:
https://github.com/dosfstools/dosfstools/commit/c598354
=> sdcard_image-rpi.bbclass: shorten the default BOOTDD_VOLUME_ID

conf/machine/include/rpi-base.inc, recipes-bsp/common/raspberrypi-firmware.inc, recipes-kernel/linux/linux-raspberrypi_5.10.bb
Fixes issues with the ARM-based KMS driver on the RPi4
Upgrade kernel and firmware to the current state of affairs to fix regression in the I2C controller.
Add missing overlay files to the boot partition. In particular "overlay_map" needed to be in the overlays folder.
=> Kernel 5.10.17

conf/layer.conf
master can only be validated with latest WIP oe-core releases so drop
gatesgrath which is now a dedicated release, soon hardknott will be out
too but for master needs its fine, while hear add honister ( fall 2021 )
release too
=> layer.conf: Drop gatesgarth and add honister to LAYERSERIES_COMPAT

recipes-core/udev/udev-rules-rpi/99-com.rules
Fix below error:
/etc/udev/rules.d/99-com.rules:10 Invalid value "/bin/sh -c
'ALIASES=/proc/device-tree/aliases; if cmp -s $ALIASES/uart0
$ALIASES/serial0; then echo 0;elif cmp -s $ALIASES/uart0
$ALIASES/serial1; then echo 1; else exit 1; fi'" for PROGRAM (char 58:
invalid substitution type)
Signed-off-by: Changqing Li <changqing.li@windriver.com>
=> 99-com.rules: fix error invalid substitution type

recipes-bsp/bootfiles/rpi-config_git.bb
Hi,
I opened a thread in raspberrypi forum: https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=298129 regarding the issue tackled in https://github.com/agherzan/meta-raspberrypi/commit/74deec51ded5b22b31b69b30537a6e9ed0997aea, and I got answered that there could be a "4K limit on reading config.txt in certain circumstances", and there was a similar case in which another variable was affected: https://github.com/raspberrypi/firmware/issues/1012
They also suggested to do not use the commented version file because it can very slightly increase the booting time as the firmware has more to parse.
Regards
=> rpi-config: comment updated

kas-poky-rpi.yml
mklibs is no longer supported, see [1]
[1] - http://git.openembedded.org/openembedded-core/commit/meta/classes?id=908df863b419d1cad7317153101fc827e7e3a354
Signed-off-by: Pierre-Jean Texier <texier.pj2@gmail.com>
=> kas: remove 'image-mklibs' from USER_CLASSES list

conf/layer.conf, recipes-kernel/linux/linux-raspberrypi-dev.bb, recipes-kernel/linux/linux-raspberrypi_5.10.bb, recipes-kernel/linux/linux-raspberrypi_5.4.bb
Tested by building virtual/kernel with and without
`PREFERRED_PROVIDER_virtual/kernel = "linux-raspberrypi-dev"`
=> [gatesgarth] Backports from master

recipes-graphics/libva/libva_%.bbappend
libva: Fix for when using `userland`
Fixes #842 - failing build of libva when using `userland` recipe.
Fix is same as: https://github.com/agherzan/meta-raspberrypi/commit/ac16b0e9d713bcc4ee0e976259064d1a318a5aac
Signed-off-by: Matt Hammond <matt.hammond@bbc.co.uk>
=> libva: Fix for when using `userland`

recipes-bsp/bootfiles/rpi-cmdline.bb
The cmdline.txt file generated by this recipe includes machine-specific information so we should set PACKAGE_ARCH appropriately.
=> Make rpi-cmdline package machine-specific

recipes-bsp/bootfiles/rpi-cmdline.bb
`CMDLINE_ROOT_FSTYPE` can be used to overwrite only the `rootfstype` in `CMDLINE`.
=> rpi-cmdline: Make rootfstype easier to customize

kas-poky-rpi.yml
Since commit 5452f1ba337685cf89d3429e08255450ab90b96f ("local.conf.sample: Bump version so users update their config") in OE-Core,
we need to update the default local.conf due to the new syntax.
Fixes:
ERROR: Error executing a python function in exec_python_func() autogenerated:
The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
0001:
*** 0002:oecore_update_localconf(d)
0003:
File: '/work/poky/meta/classes/sanity.bbclass', lineno: 56, function: oecore_update_localconf
0052:
0053:is a good way to visualise the changes."""
0054:    failmsg = d.expand(failmsg)
0055:
*** 0056:    raise NotImplementedError(failmsg)
0057:}
0058:
0059:SANITY_SITECONF_SAMPLE ?= …
=> kas: local.conf: bump CONF_VERSION variable

kas-poky-rpi.yml
Keep configuration synchronized with OE-Core, see [1].
[1] - http://git.openembedded.org/openembedded-core/commit/?id=f9719cc1c3fe9d380336e7af418daf27473b2e8b
Signed-off-by: Pierre-Jean Texier <texier.pj2@gmail.com>
=> kas: local.conf: disable prelink

recipes-graphics/userland/userland_git.bb
* last userland upgrade in:
https://github.com/agherzan/meta-raspberrypi/commit/2a25b7ef8bb7b366a93dbe42d40ebf3923d1fccc
brings this upstream commit:
https://github.com/raspberrypi/userland/commit/45a0022ac64b4d0788def3c5230c972430f6fc23
which results in:
ERROR: userland-20210623-r0 do_package: QA Issue: userland: Files/directories were installed but not shipped in any package:
/usr/man
/usr/man/man1
/usr/man/man7
/usr/man/man1/raspistill.1
/usr/man/man1/raspividyuv.1
/usr/man/man1/dtparam.1
/usr/man/man1/raspivid.1
/usr/man/man1/tvservice.1
/usr/man/man1/vcmailbox.1
/usr/man/man1/raspiyuv.1
/usr/man/man1/dtoverlay.1
/usr/man/man1/vcgencmd.1
/usr/man/man1/dtmerge.1
/usr/man/man7/raspicam.7
/usr/man/man7/raspirev.7
/usr/man/man7/raspiotp.7
/usr/man/man7/vcmailbox.7
Please set FILES such …
=> userland: package man pages in PN-doc

classes/sdcard_image-rpi.bbclass
=> sdcard_image-rpi.bbclass: Fix IMAGE_TYPEDEP override to use new syntax

recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
This change is required for the Wifi to work on the CM4
Will do a cherry pick for the dunfell branch once this lands.
=> Fix WiFi driver loading on CM4

recipes-graphics/xorg-xserver/xserver-xf86-config_%.bbappend
When updating FILES:${PN} based on an override you must use
FILES:${PN}:append:OVERRIDE as the syntax otherwise you will end up
replacing the contents of FILES:${PN} entirely.  Update to use this
syntax correctly and then only add "${sysconfdir}/X11/xorg.conf.d/*"
Reported-by: Quentin Schulz <quentin.schulz@theobroma-systems.com>
Signed-off-by: Tom Rini <trini@konsulko.com>
=> xserver-xf86-config: Correctly append to FILES:${PN}

recipes-connectivity/pi-bluetooth/pi-bluetooth_0.1.17.bb
Signed-off-by: Marcus Comstedt <marcus@mc.pp.se>
Fix the pi-bluetooth recipe to work without systemd
Added a good old initscript for `btinit`, and changed the udev rule to run `bthelper` directly instead of trying to involve systemd (only when `systemd` is not in `DISTRO_FEATURES`).
=> pi-bluetooth: Add compatibility with non-systemd builds

recipes-bsp/bootfiles/rpi-cmdline.bb, recipes-bsp/bootfiles/rpi-config_git.bb
Support Ethernet over USB
This is my first contribution to a yocto main project, so if I am missing anything please do let me know I am happy to resubmit with any missing data.
I added support for "on the go" via both config.txt and cmdline.txt
In both cases I use new configuration variables (ENABLE_DWC2_OTG, and CMDLINE_RNDIS) which is expected to be supplied in the main project's conf/local.conf. These modify the boot setup for the raspberry pi, in alignment with the recommended practise for the same setup when using Rasbian.
=> Support OTG via config.txt

recipes-bsp/bootfiles/rpi-config_git.bb, recipes-connectivity/pi-bluetooth/pi-bluetooth_0.1.17.bb, recipes-devtools/pi-blaster/pi-blaster_git.bb, recipes-devtools/python/python3-adafruit-blinka_6.2.2.bb, recipes-devtools/python/python3-adafruit-circuitpython-busdevice_5.0.5.bb, recipes-devtools/python/python3-adafruit-circuitpython-motor_3.2.6.bb, recipes-devtools/python/python3-adafruit-circuitpython-motorkit_1.6.1.bb, recipes-devtools/python/python3-adafruit-circuitpython-pca9685_3.3.4.bb, recipes-devtools/python/python3-adafruit-circuitpython-register_1.9.4.bb, recipes-devtools/python/python3-adafruit-platformdetect_3.1.1.bb, recipes-devtools/python/python3-adafruit-pureio_1.1.8.bb, recipes-devtools/python/python3-rtimu_git.bb, recipes-graphics/raspidmx/raspidmx_git.bb, recipes-graphics/userland/userland_git.bb, recipes-kernel/bluez-firmware-rpidistro/bluez-firmware-rpidistro_git.bb, recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb, recipes-kernel/linux/linux-raspberrypi-dev.bb, recipes-kernel/linux/linux-raspberrypi_5.10.bb, recipes-multimedia/omxplayer/omxplayer_git.bb
Use protocols=https for GitHub SRC_URIs using the conversion script in
openembedded-core.
Signed-off-by: Marcel Hamer <marcel@solidxs.se>
=> recipes: Update SRC_URI protocols for github

recipes-bsp/bootfiles/rpi-config_git.bb, recipes-connectivity/pi-bluetooth/pi-bluetooth_0.1.12.bb, recipes-devtools/pi-blaster/pi-blaster_git.bb, recipes-devtools/python/python3-rtimu_git.bb, recipes-graphics/userland/userland_git.bb, recipes-kernel/bluez-firmware-rpidistro/bluez-firmware-rpidistro_git.bb, recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb, recipes-kernel/linux/linux-raspberrypi-dev.bb, recipes-multimedia/omxplayer/omxplayer_git.bb
THis cherrypicks and adapts on `dunfell` the GitHub protocol change done in master:
```
commit e31fba4c96cdf819958d05875fb8733481997806
Author: Marcel Hamer <marcel@solidxs.se>
Date:   Fri Nov 5 12:18:39 2021 +0100
recipes: Update SRC_URI protocols for github
Use protocols=https for GitHub SRC_URIs using the conversion script in
openembedded-core.
Signed-off-by: Marcel Hamer <marcel@solidxs.se>
```
=> [dunfell] Cherry-pick github change in master

recipes-core/udev/udev-rules-rpi/99-com.rules
fix below error:
/etc/udev/rules.d/99-com.rules:10 Invalid value "/bin/sh -c
'ALIASES=/proc/device-tree/aliases; if cmp -s $ALIASES/uart0
$ALIASES/serial0; then echo 0;elif cmp -s $ALIASES/uart0
$ALIASES/serial1; then echo 1; else exit 1; fi'" for PROGRAM (char 58:
invalid substitution type)
=> dunfell: 99-com.rules: fix error invalid substitution type

recipes-sato/libwpe_%.bbappend
This was removed from oe-core[1] so we pull in the change here where it
should have been in the first place.
Fixes: https://github.com/agherzan/meta-raspberrypi/issues/893
[1] https://lists.openembedded.org/g/openembedded-core/topic/84653556
=> libwpe: Migrate build workaround from oe-core

conf/machine/include/rpi-base.inc
Some machines need to have the kernel toggle a gpio when an external
power source needs to shut off power to complete a shutdown and de-energize
the processor.  gpio-poweroff provides this functionality but was omitted
from the kernel overlays brought over by the rpi-layer from the kernel.
Signed-off-by: Cameron Kellough <cameron@telemetrak.com>
=> rpi-base.inc: Added gpio-poweroff overlay.

recipes-bsp/bootfiles/rpi-config_git.bb
Fixes https://github.com/agherzan/meta-raspberrypi/pull/941 not to show fatal error for default configuration with ENABLE_UART being empty.
=> rpi-config: don't trigger bbfatal for empty ENABLE_UART

recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
Switch to using bullseye release 20210315-3+rpt3
License is pointed in different location in new repo structure WHENCE
file is gone too.
Fixes
https://github.com/YoeDistro/yoe-distro/issues/617
=> linux-firmware-rpidistro: Use bullseye branch

recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
Master branch has been renamed to buster.
This change is dunfell-specific because master follows bullseye which
diverted from ex-master quite a lot.
Related: https://github.com/RPi-Distro/firmware-nonfree/issues/20
Signed-off-by: Pavel Zhukov <pavel.zhukov@huawei.com>
=> Use buster branch instead of master

conf/machine/raspberrypi4-64.conf, conf/machine/raspberrypi4.conf
These boards use a slightly different chip which requires additional firmware to be present.
See: https://github.com/agherzan/meta-raspberrypi/issues/793#issuecomment-972959002
=> conf/machine: add variant Wi-Fi/BT drivers for CM4 and Pi 400

recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
Branch has been renamed to buster in source repo.
Also setting protocol to https as GitHub is migrating
away from unencrypted git protocol
=> linux-firmware-rpidistro: set branch to buster

lib/oeqa/runtime/cases/parselogs_rpi.py, recipes-kernel/linux/linux-raspberrypi_5.10.bb
The old messages are no longer necessary and there is a new error
regarding sda and sda1 not being able to open blockdev this seems a
kernel problem which has been reported [1], until its understood better
lets ignore it.
[1] https://github.com/raspberrypi/linux/issues/4722
=> parselogs: Update the error regexps to 5.10 kernel

recipes-graphics/wayland/weston-init.bbappend
launching with --continue-without-input helps starting weston
without keyboard/mouse
=> weston-init: Add --continue-without-input option to weston

recipes-graphics/mesa/mesa_%.bbappend
This enables building mesa Vulkan Broadcom driver for v3d.
Signed-off-by: Joel Winarske <joel.winarske@gmail.com>
=> mesa: Broadcom v3d Vulkan driver

recipes-kernel/linux/linux-raspberrypi_5.10.bb
Upgrade linux-raspberrypi to 5.10.83.
Fixes #957.
=> linux-raspberrypi: Upgrade to 5.10.83

conf/machine/raspberrypi4-64.conf
rpi4 SOC does not have AES Crypto in H/W
Fixes Issue #964
=> raspberrypi4-64: Switch to using cortexa72-crc default tune

conf/machine/raspberrypi0-2w.conf
Added new machine configuration for Raspberry Pi Zero 2 W in 32bit mode.
Signed-off-by: Mauro Anjo <maurosanjo@gmail.com>
=> machine: add Pi Zero 2 W 32bits

conf/machine/include/rpi-base.inc, docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-config_git.bb, recipes-bsp/gpio-shutdown/files/bind_gpio_shutdown.tab, recipes-bsp/gpio-shutdown/files/gpio-shutdown-keymap.sh, recipes-bsp/gpio-shutdown/gpio-shutdown.bb
Enable gpio-shutdown functionality, see https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README for reference.
In short, this feature includes the gpio-shutdown.dtbo. If systemd init is enabled, no futher configuration is needed. However if (the default) SysV init is used, the GPIO input requires additional binding which is handled by recipes-bsp/gpio-shutdown/gpio-shutdown.bb:
1. gpio-shutdown sends key code 116 which is bound to KeyboardSignal and injected into the keymap in gpio-shutdown-keymap.sh. This init script is executed at runlevel S
2. SysV inittab needs instructions what to do when KeyboardSignal is received. This is implemented by bind_gpio_shutdown.tab which is deployed to /etc/inittab.d/
The feature is enabled by variable …
=> recipes-bsp: Add support for gpio-shutdown

conf/machine/raspberrypi4-64.conf
After commits ca50267ab568 & 03cebdd7ef92 in openembedded-core, the `cortexa72-crc` tune is no longer available and the `cortexa72` tune includes the crc extension by default. Update the raspberrypi4-64 machine config to handle these changes.
=> raspberrypi4-64: Switch to cortexa72 tune

recipes-multimedia/picamera-libs/picamera-libs.bb, recipes-multimedia/python3-picamera/python3-picamera_git.bb
python3-picamera : recipe for python picamera library.
python3-colorzero: recipe for python colorzero library, required by picamera
picamera-libs    : recipe raspberry pi firmware which are required by picamera.
Closes: #959
Signed-off-by: bhargavthriler <bhargavthriler@gmail.com>
Created recipe for python picamera library. Along with it created 2 more, python colorzero and picamera-libs.
=> Add picamera support

recipes-devtools/python/rpi-gpio_0.7.0.bb, recipes-multimedia/picamera-libs/picamera-libs.bb, recipes-multimedia/python3-picamera/python3-picamera_git.bb
https://github.com/agherzan/meta-raspberrypi/pull/983 introduced these
recipes however these are not generic packages that can be used on non-rpi machines
therefore mark them so. It helps in using this SOC layer with other SOC
layers in a distro
=> picamera-libs,python3-picamera: Limit visibility to rpi machines

conf/machine/include/rpi-base.inc
Hi all,
this is a RFC to be able to add i2c-gpio overlays.
Defining I2C_GPIO_CONFIG = "bus=7,i2c_gpio_sda=6,i2c_gpio_scl=5"
Will configure i2c-7 bus to use gpio 6 as SDA and gpio 5 as SCL
This way of configuration has the drawback to not be able to define more then one bus. Should we define an array? I saw some other defines using _X so we could use e.g
I2C_GPIO_CONFIG_X = "i2c_gpio_sda=6,i2c_gpio_scl=5" to define bus X and check a fix list of such variables?
I'm also not sure if we should abstract the command line even further?
I2C_GPIO_CONFIG_X_SCL=6
I2C_GPIO_CONFIG_X_SDA=5
Or something like that?
=> bootfiles: allow i2c-gpio overlay

dynamic-layers/openembedded-layer/recipes-devtools/python3-adafruit-blinka_6.2.2.bb, dynamic-layers/openembedded-layer/recipes-devtools/python3-adafruit-circuitpython-busdevice_5.0.5.bb, dynamic-layers/openembedded-layer/recipes-devtools/python3-adafruit-circuitpython-motor_3.2.6.bb, dynamic-layers/openembedded-layer/recipes-devtools/python3-adafruit-circuitpython-motorkit_1.6.1.bb, dynamic-layers/openembedded-layer/recipes-devtools/python3-adafruit-circuitpython-pca9685_3.3.4.bb
it provides prebuilts which are linked against glibc. so disable it for
musl
Fixes
microcontroller/bcm283x/pulseio/libgpiod_pulsein contained in package python3-adafruit-blinka requires libc.so.6(GLIBC_2.4), but no providers found in RDEPENDS:python3-adafruit-blinka? [file-rdeps]
=> python3-adafruit-blinka: Disable on musl

recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_%.bbappend
* libmms was removed with 1.20.0 upgrade in:
https://git.openembedded.org/openembedded-core/commit/?id=76433d3628cbad311b428a57b25b4e2701ee513b
* fixes:
```
ERROR: gstreamer1.0-plugins-bad-1.20.0-r0 do_configure: QA Issue: gstreamer1.0-plugins-bad: invalid PACKAGECONFIG: libmms [invalid-packageconfig]
```
* faad now requires gpl to be enabled:
```
| ../gst-plugins-bad-1.20.0/ext/faad/meson.build:1:0: ERROR: Feature faad cannot be enabled:
|   Plugin faad explicitly required via options but GPL-licensed plugins disabled via options.
|   Pass option -Dgpl=enabled to Meson to allow GPL-licensed plugins to be built.
```
=> gstreamer1.0-plugins-bad: remove libmms PACKAGECONFIG and add gpl

classes/sdcard_image-rpi.bbclass, conf/machine/include/rpi-base.inc, docs/extra-build-config.md, recipes-bsp/common/raspberrypi-firmware.inc, recipes-kernel/linux/linux-raspberrypi_5.10.bb, recipes-kernel/linux/linux-raspberrypi_5.15.bb
* bump both 5.10 and 5.15 kernel recipes
* use a stable release tarball from raspberrypi deb repository for the raspberrypi firmware recipe
* ~~include support for bcm2711-rpi-cm4s (superseeds https://github.com/agherzan/meta-raspberrypi/pull/995)~~ Dropped as it doesn't support 64bit (as the initial PR proposed it).
* fix inconsistency between wic and sdimg images (partially fixes https://github.com/agherzan/meta-raspberrypi/issues/1013)
=> A set of various updates and fixes

recipes-devtools/python/python3-adafruit-circuitpython-register_1.9.4.bb, recipes-devtools/python/python3-adafruit-platformdetect_3.1.1.bb, recipes-devtools/python/python3-adafruit-pureio_1.1.8.bb, recipes-devtools/python/python3-rtimu_git.bb, recipes-devtools/python/rpi-gpio_0.7.0.bb
OE-Core has improved packaging the whl files therefore remove the
band-aids.
=> python: Unbolt wheel packaging PIP_INSTALL_PACKAGE band-aids

recipes-bsp/u-boot/files/0001-rpi-always-set-fdt_addr-with-firmware-provided-FDT-address.patch, recipes-bsp/u-boot/u-boot_%.bbappend
The Raspberry firmware prepares the FDT blob in memory at an address that
depends on both the memory size and the blob size.
For details see description in the patch itself.
The patch is not yet upstream, but has already been submitted by the original
author: https://lore.kernel.org/all/20210512123945.25649-1-m.salvini@koansoftware.com/
For me, the described problem occurs in conjunction with RAUC, which uses the
following U-Boot script: https://github.com/rauc/meta-rauc-community/blob/master/meta-rauc-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/boot.cmd.in
As soon as I add an overlay the fdt_addr changes and the system does not boot
anymore.
=> u-boot: always set fdt_addr with firmware-provided FDT address

docs/extra-build-config.md
The `rtc` machine feature is "considered" by default for all the
machines we provide until now. This can confuse people who would want an
RTC device attached to a RaspberryPi board[1]. Clarify this via
documentation.
[1] https://github.com/agherzan/meta-raspberrypi/issues/1010
=> docs: Add information for RTC devices

docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-cmdline.bb
I have added a new variable to be parsed and added to cmdline.txt that allows us to take advantage of the isolcpus capabilities typically used for real time tasks
I added a new variable to be read from conf/local.conf and added to cmdline.txt via the rpi-cmdline.bb recipe
=> rpi-cmdline: Add option to append isolcpus to cmdline.txt

recipes-kernel/linux/linux-raspberrypi.inc
This is so that uboot fit images have an entry point that matches the
LOADADDR that everything is expecting.
=> linux-raspberrypi: add UBOOT_ENTRYPOINT to match LOADADDR

README.md
Version 1.0 of kas is not the latest anymore.
Signed-off-by: Jan Vermaete <jan.vermaete@gmail.com>
=> docs: link to latest documentation of kas

dynamic-layers/meta-python/recipes-devtools/python/python3-sense-hat_2.2.0.bb
Fixes
WARNING: python3-sense-hat-2.2.0-r0 do_populate_lic: QA Issue: python3-sense-hat: No generic license file exists for: BSD in any provider [license-exists]
=> python3-sense-hat: Use specific BSD license

recipes-kernel/kmod/kmod_%.bbappend
The RaspberryPi default Linux kernel configuration uses xz for
compressing kernel modules[1]. This was introduced in 5.15. We need the
respective support in kmod too.
[1]https://github.com/raspberrypi/linux/pull/4991
Fixes: https://github.com/agherzan/meta-raspberrypi/issues/1054
=> kmod: Enable xz compression

recipes-kernel/kmod/kmod_%.bbappend
This reverts commit c97a9e34abf23d871903481ac1867efec9abf090 as it was fixed properly in oe-core.
=> Revert "kmod: Enable xz compression"

.github/workflows/mirror.yml
This has full support for env variables.
=> ci: Migrate worflow to using latest git-mirror-me-action revision

recipes-bsp/bootfiles/rpi-cmdline.bb
Otherwise the shell snippet fails with `bad syntax` when `CMDLINE`
contains special characters like `${...}` (useful to insert a U-Boot
variable in `cmdline.txt`).
Modify `do_compile` so that special characters `${...}` are accepted for `CMDLINE`.
Getting `CMDLINE` variable through Python with `d.getVar()`
=> rpi-cmdline: do_compile: Use pure Python syntax to get `CMDLINE`

recipes-bsp/bootfiles/rpi-cmdline.bb
=> [kirkstone] rpi-cmdline: do_compile: Use pure Python syntax to get `CMDLINE`

recipes-bsp/common/raspberrypi-firmware.inc
Please make backport to Kirkstone branch
Signed-off-by: Vinicius Aquino <vinicius.aquino@ossystems.com.br>
Updated the Firmware RaspberryPi version.
Changing the version to fetch and adapting the sha256sum to the new version.
=> raspberrypi-firmware: Update to 20220830 snapshot

recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro/0001-Default-43455-firmware-to-standard-variant.patch, recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
The firmware for 43455 is loaded as a symlink: brcmfmac43455-sdio.bin. This symlink is now broken as the debian package handles the right target of this symlink through a postinstall.  We don't have that logic here so we default to the standard variant.
This issue was reported upstream: https://github.com/RPi-Distro/firmware-nonfree/issues/26
=> linux-firmware-rpidistro: Fix wireless on Raspberry Pi 4

dynamic-layers/multimedia-layer/recipes-multimedia/rpidistro-vlc/rpidistro-vlc_3.0.12.bb, recipes-multimedia/rpidistro-ffmpeg/rpidistro-ffmpeg_4.3.2.bb
enable mmal only when using userland graphics
Fixes builds on non-rpi machines e.g.
ERROR: Nothing PROVIDES 'userland' (but /mnt/jenkins/workspace/yocto-world-glibc/sources/meta-raspberrypi/recipes-multimedia/rpidistro-ffmpeg/rpidistro-ffmpeg_4.3.2.bb DEPENDS on or otherwise requires it) userland was skipped: incompatible with machine qemumips (not in COMPATIBLE_MACHINE) NOTE: Runtime target 'rpidistro-ffmpeg' is unbuildable, removing...
=> rpidistro-vlc,rpidistro-ffmpeg: Limit scope to just rpi machines

docs/extra-build-config.md
Explains that PREFERRED_PROVIDER_ffmpeg/vlc can be used to select an implementation of ffmpeg
or vlc. Also adds information on how vlc mmal_vout plugin may be utilized. As well as how to expose rpidistro-vlc recipe.
=> docs: add info for raspberrypi distro vlc

.github/workflows/yocto-builds.yml, classes/sdcard_image-rpi.bbclass, conf/machine/include/rpi-base.inc, conf/machine/include/rpi-default-versions.inc, conf/machine/raspberrypi-armv7.conf, conf/machine/raspberrypi-armv8.conf, conf/machine/raspberrypi.conf, conf/machine/raspberrypi0-2w.conf, conf/machine/raspberrypi2.conf, conf/machine/raspberrypi3-64.conf, docs/layer-contents.md, recipes-kernel/linux/linux-raspberrypi-v7.inc, recipes-kernel/linux/linux-raspberrypi-v7_5.10.bb, recipes-kernel/linux/linux-raspberrypi-v7_5.15.bb, recipes-kernel/linux/linux-raspberrypi.inc, recipes-kernel/linux/linux-raspberrypi_5.15.bb
This introduces two new machines:
* raspberrypi-armv7.conf aims at supporting all the ARMv7 Raspberry Pi boards
* raspberrypi-armv8.conf aims at supporting all the ARMv8 Raspberry Pi boards.
This initial support was tested on:
* Raspberry Pi 4 Model B
* Raspberry Pi 3 Model B
* Raspberry Pi 0 2 WiFi
Tests:
* Boot
* WiFi
* BT
* Modules load
Known broken/unsupported
* u-boot support
Landed in oe-core/master ~~PR is in draft mode due to pending `oe-core` changes to correctly handle depmod-ing multiple kernel module sets:~~
* https://lists.openembedded.org/g/openembedded-core/message/170505
* https://lists.openembedded.org/g/openembedded-core/message/170506
* https://lists.openembedded.org/g/openembedded-core/message/170507
* https://lists.openembedded.org/g/openembedded-core/message/170508
=> Add support for multi kernel Raspberry Pi machines

conf/machine/include/rpi-base.inc, conf/machine/raspberrypi-armv8.conf, conf/machine/raspberrypi4-64.conf
- Added `(broadcom/)bcm2711-rpi-cm4s.dtb` to `RPI_KERNEL_DEVICETREE` as preparation for https://github.com/balena-os/balena-raspberrypi/pull/913.
=> Include the device tree for Raspberry Pi CM4S

recipes-bsp/bootfiles/rpi-cmdline.bb
Fixes #1095 where setting cma to a lower value affects the ability of libcamera-apps to capture higher resolution images.
=> rpi-cmdline: Leave cma value to kernel default

dynamic-layers/multimedia-layer/recipes-multimedia/libcamera/libcamera.bbappend, recipes-multimedia/libcamera-apps/rpi-libcamera-apps_git.bb
Added a recipe for Raspberry Pi's libcamera-apps. Tested with poky/oe master. I haven't built or tested optional dependencies to qt, tensorflow lite, and opencv. These should be considered work in progress, for those who require these dependencies to enhance and test, and submit future PRs.
=> rpi-libcamera-apps: add new recipe

conf/machine/include/rpi-base.inc
This patch is based on an analog patch from Christopher Boyd <xpboyd@gmail.com> committed at meta-freescale. (see https://github.com/Freescale/meta-freescale/commit/954d7a7d7afc3ad4950eb0fd354a6f4bd06d911a)
Signed-off-by: Oliver Lang <quantenkeks@gmail.com>
=> rpi-base.inc: handle empty/undefined KERNEL_DEVICETREE

conf/machine/raspberrypi4-64.conf
* it matches the default from tune-cortexa72.inc: $ grep DEFAULTTUNE openembedded-core/meta/conf/machine/include/arm/armv8a/tune-cortexa72.inc DEFAULTTUNE ?= "cortexa72"
* the assignment was introduced in: https://github.com/agherzan/meta-raspberrypi/commit/cd234925fa59197a52f4cb5011902ab5867c684f to switch to cortexa72-crc, but this change was effectively reverted in: https://github.com/agherzan/meta-raspberrypi/commit/42ef0f504604a4ba1dcad689de804ee8bf8a7afe by setting it back to default "cortexa72".
=> raspberrypi4-64: drop DEFAULTTUNE assignment

dynamic-layers/multimedia-layer/recipes-multimedia/rpidistro-vlc/rpidistro-vlc_3.0.12.bb, recipes-multimedia/rpidistro-ffmpeg/rpidistro-ffmpeg_4.3.2.bb
Connected to [VLC on RaspberryPI0w2 with framebuffer only](https://github.com/agherzan/meta-raspberrypi/issues/1117)
From [VLC on RaspberryPI0w2 with framebuffer only](https://github.com/agherzan/meta-raspberrypi/issues/1117) fixes
```
ERROR: Nothing PROVIDES 'rpidistro-ffmpeg'
rpidistro-ffmpeg was skipped: incompatible with host arm-project-linux-gnueabi (not in COMPATIBLE_HOST)
```
Removed single quotes from regex string as it appears to make the expression invalid. Thus, leading to above error.
=> rpidistro-vlc,rpidistro-ffmpeg: update COMPATIBLE_HOST regex

conf/machine/include/rpi-default-providers.inc
**The Error**
ERROR: Multiple .bb files are due to be built which each provide libav/libpostproc:
/../../meta-raspberrypi/recipes-multimedia/rpidistro-ffmpeg/rpidistro-ffmpeg_4.3.4.bb
/../../openembedded-core/meta/recipes-multimedia/ffmpeg/ffmpeg_5.1.2.bb
**How I solved it**
Ensures bitbake understands which recipe to utilize by specifying
rpidistro-ffmpeg as the preferred provider.
=> rpi-default-providers: add libav and libpostproc

recipes-graphics/wayland/weston_%.bbappend
* Weston 10 (Yocto Langdale) fails to build with userland drivers when the packageconfig options `egl` or `clients` are enabled, and those are enabled by default. So disable them by default when building with `DISABLE_VC4GRAPHICS=1`
This is the build failure that happens without this patch:
```
| [105/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/launcher-direct.c
| [106/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/launcher-weston-launch.c
| [107/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/bindings.c
| [108/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c …
```
=> Disable Weston packageconfig options that fail to build with userland drivers

recipes-kernel/linux/linux-raspberrypi.inc
COMPATIBLE_MACHINE is expected to be overridden by linux-raspberrypi-v7.inc for linux-raspberrypi-v7 machine this however does not work because linux-raspberrypi-v7_5.15.bb includes linux-raspberrypi-v7.inc and linux-raspberrypi.inc ( via linux-raspberrypi_5.15.bb) and setting from linux-raspberrypi.inc takes precedence over one coming from linux-raspberrypi-v7.inc as a result linux-raspberrypi-v7 kernel recipe becomes available for raspberrypi4 machine as well, this recipe however needs certain defines e.g.RASPBERRYPI_v7_KERNEL which are only available in raspberrypi-armv7.conf
=> linux-raspberrypi.inc: Weakly assign COMPATIBLE_MACHINE

recipes-connectivity/pi-bluetooth/pi-bluetooth/0001-bthelper-correct-path-for-hciconfig-under-Yocto.patch
* fixes: WARNING: pi-bluetooth-0.1.17-r0 do_patch: QA Issue: Malformed Upstream-Status in patch meta-raspberrypi/recipes-connectivity/pi-bluetooth/pi-bluetooth/0001-bthelper-correct-path-for-hciconfig-under-Yocto.patch Please correct according to https://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines#Patch_Header_Recommendations:_Upstream-Status : Upstream-Status: Inapproprate [OE-specific] [patch-status-noncore]
=> pi-bluetooth: fix typo in Upstream-Status

recipes-graphics/raspidmx/raspidmx/0001-gitignore-add-archives-from-lib-directory.patch, recipes-graphics/raspidmx/raspidmx/0002-add-install-targets-to-Makefiles.patch, recipes-graphics/raspidmx/raspidmx/0003-switch-to-pkg-config.patch, recipes-graphics/raspidmx/raspidmx/0004-add-libvchostif-to-link.patch, recipes-graphics/raspidmx/raspidmx/0005-change-library-linking-order.patch, recipes-graphics/raspidmx/raspidmx/0006-game-Makefile-install-sample-png-files.patch, recipes-graphics/raspidmx/raspidmx/0007-Makefile-reorganize.patch, recipes-graphics/userland/files/0022-all-host_applications-remove-non-existent-projects.patch, recipes-graphics/userland/files/0023-hello_pi-optionally-build-wayland-specific-app.patch, recipes-multimedia/omxplayer/omxplayer/0005-Don-t-require-internet-connection-during-build.patch, recipes-multimedia/omxplayer/omxplayer/0006-Prevent-ffmpeg-configure-compile-race-condition.patch
* now I've used the right tool to hopefully find them all in one go:
```
../openembedded-core/scripts/contrib/patchreview.py .
Total patches found: 70
Patches missing Signed-off-by: 17 (24%)
Patches with malformed Signed-off-by: 0 (0%)
Patches missing CVE: 1 (1%)
Patches missing Upstream-Status: 32 (46%)
Patches with malformed Upstream-Status: 0 (0%)
Patches in Pending state: 8 (11%)
```
=> raspidmx, userland, omxplayer: Fix Upstream-Status formatting

recipes-graphics/mesa/mesa-demos_%.bbappend
Enable build of mesa-demos for userland graphics drivers
* mesa-demos can be built fine if both `gles1` and `egl` options are disabled. This allows to have utilities like `glxinfo` or `glxgears`
=> Enable build of mesa-demos for userland graphics drivers

conf/machine/include/rpi-default-versions.inc, recipes-core/psplash/files/framebuf.conf, recipes-core/psplash/psplash_%.bbappend, recipes-kernel/linux/linux-raspberrypi-v7_6.1.bb, recipes-kernel/linux/linux-raspberrypi_6.1.bb
Default to 6.1 as well now that pspash is fixed
=> linux-raspberrypi: Add recipes for 6.1 kernel

conf/machine/raspberrypi-cm.conf, conf/machine/raspberrypi0-2w-64.conf, conf/machine/raspberrypi0-2w.conf, conf/machine/raspberrypi0.conf, conf/machine/raspberrypi3-64.conf, conf/machine/raspberrypi4-64.conf
Prepending new definitions should be preferred to assignment, as it is simpler and more conducive to defining new machine configurations that reuse these configurations.
I posted an initial draft of this patch (with the required `Signed-Off-By` line) to the yocto mailing list as well, but I thought a PR might elicit a more expedient response.
Also, I tested this on the `kirkstone` branch with the `raspberrypi{3,4}-64` machines included in my own custom machine configurations, but these changes should apply cleanly on all active branches and be safe to use with all configurations.
=> machines: simplify MACHINEOVERRIDES definitions

conf/machine/include/rpi-base.inc, docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-config_git.bb
I would like to see support for the Raspberry Pi Camera Module v3 which uses the imx708 sensor. Therefore, I added the required device tree overlay and config. I am not able to test this right now but it would be great if an admin could verify this patch.
=> Add support for Raspberry Pi Camera Module v3

kas-poky-rpi.yml
Naming changed in Yocto.  And it avoids a warning during the run.
=> kas-poky-rpi.yml: renamed ABORT to HALT

conf/machine/include/rpi-base.inc
It can be useful to disable the WiFi for hardening reasons. And it probably lower the power consumption a bit.
=> rpi-base.inc: add the disable-wifi device tree overlay

dynamic-layers/multimedia-layer/recipes-multimedia/libcamera/libcamera_%.bbappend
* libcamera was updated in meta-oe in: https://git.openembedded.org/meta-openembedded/commit/?id=4e0281797277cf44287de93618c51e4a219fac75
* now it was failing with:
meson.build:3:0: ERROR: Options "raspberrypi" are not in allowed choices: "all, auto, imx8-isi, ipu3, rkisp1, rpi/vc4, simple, uvcvideo, vimc"
because raspberrypi support was updated and renamed to rpi/vc4 in: https://github.com/raspberrypi/libcamera/commit/726e9274ea95fa46352556d340c5793a8da51fcd
=> libcamera: update PACKAGECONFIG for libcamera-0.1.0

dynamic-layers/multimedia-layer/recipes-multimedia/rpidistro-vlc/files/0009-demux-dash-include-cstdint-needed-for-uint64_t.patch, dynamic-layers/multimedia-layer/recipes-multimedia/rpidistro-vlc/rpidistro-vlc_3.0.17.bb
Build failure occurring with gcc version 13.1.1.
Add patch to fix builds with latest gcc in OE-core.
=> rpidistro-vlc: fix error uint64_t does not name

conf/machine/include/rpi-base.inc
psplash-raspberrypi does not exist anymore, we use psplash from core
=> rpi-base: Remove customizing SPLASH var

conf/machine/include/rpi-base.inc
wic images depend on the kernel device trees, and therefore should depend on virtual/kernel:do_deploy to make sure these are present in the deploy directory.
Most of the time, this dependency is satisfied indirectly since a rootfs image will depend on the kernel, but add it explicitly for the cases where it is not.
=> rpi-base: Fix wic image kernel dependency

.readthedocs.yaml
This fixes:
The configuration key "build.os" is required to build your
documentation. Read more at
https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
=> docs: Fix ReadTheDocs builds.os requirement

recipes-kernel/linux/files/default-cpu-governor.cfg, recipes-kernel/linux/linux-raspberrypi.inc
* The defconfigs from the RPi Kernel set `powersave` as the default CPU governor, which is a bad idea as that reduces performance by setting the CPU frequency to the minimum one.
* In case of a Yocto build user-space is not configured by default to change the CPU governor, so `powersave` will remain the CPU governor and it will slow down everything.
* I submitted a fix for those defconfigs to upstream here: https://github.com/raspberrypi/linux/pull/5666 However, we shouldn't wait until that is accepted and backported to all the stable branches (if ever is).
* This patch unsets the selection of `powersave` as the default CPU governor.
* Then the CPU governor that will be selected as default after this patch will be the Linux's default one that is either `ondemand` or `schedutil` depending …
=> linux-raspberrypi: stop setting powersave as the default CPU governor

conf/machine/include/rpi-base.inc
This fix is needed to bring the complete dependency chain in order to guarantee the recursive runtime dependencies [1] of do_populate_lic_deploy in do_populate_lic will run as expected.
[1] _openembedded-core/meta/classes-recipe/license_image.bbclass:do_populate_lic_deploy[recrdeptask] += "do_populate_lic do_deploy"_
Fix the following image build issues:
```
ERROR: lmp-base-console-image-1.0-r0 do_populate_lic_deploy: Couldn't find license information for dependency rpi-config
```
=> rpi-base: Adds EXTRA_IMAGEDEPENDS to fix the image task do_populate_lic_deploy

recipes-kernel/linux/files/default-cpu-governor.cfg, recipes-kernel/linux/linux-raspberrypi.inc
This cherry-picks 0a4a68dba67442fbe3832a9d0764fa4ba7d08fba from master into Mickledore branch
=> [Micledore] backport patch: linux-raspberrypi: stop setting powersave as the default CPU governor

recipes-bsp/bootfiles/rpi-config_git.bb
Upgrade to the latest version of the repository with includes the following improvements of the template for config.txt:
- update revision and date stamp
- additon of dtoverlay
- general updates
This work was sponsored by GOVCERT.LU.
Upgrade to the latest version of https://github.com/Evilpaul/RPi-config
While working on https://github.com/agherzan/meta-raspberrypi/pull/1237 I noticed that recipe `rpi-config` uses an older version and decided to upgrade the template for `config.txt` to the latest available version. The primary reason is that in the new version the date at the beginning of `config.txt` has been changed for `Revision 16, 2013/06/22` to `Revision 17, 2021/08/15`. Obviously there have been many additions in general to `config.txt` since …
=> rpi-config: Upgrade to tip of tree

dynamic-layers/multimedia-layer/recipes-multimedia/rpidistro-vlc/files/3010-po-Fix-typos-in-oc.po-for-gettext-compatibility.patch, dynamic-layers/multimedia-layer/recipes-multimedia/rpidistro-vlc/rpidistro-vlc_3.0.17.bb
Fixes compilation issue that occurs when
building with the latest version OE-core.
Attempted to apply upstream after failing decided
to implement it myself, but add link to upstream fix
=> rpidistro-vlc: add new patch po-Fix-typos-in-oc

recipes-bsp/bootfiles/rpi-config/0001-config.txt-reintroduce-start_x.patch, recipes-bsp/bootfiles/rpi-config_git.bb
Add a patch to reintroduce configuration start_x. This patch has been submitted to the upstream of of the RPi-config GitHub repo: https://github.com/Evilpaul/RPi-config/pull/8
This work was sponsored by GOVCERT.LU.
Reintroduce configuration `start_x` to `config.txt` following the reported problem by @holagvk: https://github.com/agherzan/meta-raspberrypi/pull/1247#issuecomment-1817370348
Temporary with a patch until hopefully the change is in the upstream: https://github.com/Evilpaul/RPi-config/pull/8
=> rpi-config: reintroduce start_x

docs/extra-build-config.md
I fixed the documentation for initramfs: I tried creating an initramfs image following the official (latest) documentation of the meta-raspberrypi layer but there was a dependency loop error caused by the `IMAGE_FSTYPES_pn-${INITRAMFS_IMAGE}` variable not following the latest syntax for overrides.
I fixed the doc by using the `IMAGE_FSTYPES:pn-${INITRAMFS_IMAGE}` syntax for the override.
=> docs: fix syntax for overriding fs type for initramfs image

docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-cmdline.bb, recipes-bsp/rpi-u-boot-scr/files/boot.cmd.in, recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr.bb
Raspberry Pi 4 board can boot the image from USB memory. But, current meta-raspberrypi supports only SD boot.
This commit allows switching SD boot to other device. For example, if you want to use USB boot, please define the following parameters in your conf/local.conf file.
CMDLINE_ROOT_PARTITION = "/dev/sda2"
BOOT_MEDIA = "usb"
I checked 
This commit is a proposal then I wrote some description in commit message
=> Enable to support USB boot

recipes-devtools/bcm2835/bcm2835_1.73.bb
Update to version 1.73:
- Fixed some inconsistent indenting in bcm2835.c that triggers warnings for some people.
- Added Timeout checks to bcm2835_i2c_write() in case of IO problems. New reason code BCM2835_I2C_REASON_ERROR_TIMEOUT added.
I updated bcm2835
Updated the recipe from 1.71 to 1.73 and performed very basic quick tests on Raspberry Pi Zero 2 64-bit.
=> bcm2835: update 1.71 -> 1.73

docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-config_git.bb
Fixes #1264
The users can now define CAN interrupt pins that are different from the hard-coded one.
I defined two more CAN variables that let users configure the CAN interrupt pins depending by the module that they used (or by their custom boards). It is similar to CAN_OSCILLATOR. I also added these variables to the documentation
Once this is merged I will cherry-pick this commit to Kirkstone (because I need this change)
=> Define CAN interrupt pins

dynamic-layers/multimedia-layer/recipes-multimedia/libcamera-apps/libcamera-apps/0001-utils-version.py-use-usr-bin-env-in-shebang.patch, dynamic-layers/multimedia-layer/recipes-multimedia/libcamera-apps/libcamera-apps/0002-Revert-Support-compressed-pixel-formats-when-saving-.patch, dynamic-layers/multimedia-layer/recipes-multimedia/libcamera-apps/libcamera-apps_git.bb
* it's failing to build since the upgrade in: https://git.openembedded.org/meta-openembedded/commit/?id=711c6fbce39df685225bca081c5f42bae2de658b
* fixes ../git/core/libcamera_app.cpp: In member function 'void LibcameraApp::ConfigureViewfinder()': ../git/core/libcamera_app.cpp:327:25: error: 'class libcamera::CameraConfiguration' has no member named 'transform'
327 |         configuration_->transform = options_->transform;
|                         ^~~~~~~~~
* be aware that the repository and libraries were removed in 1.4.0 version with: https://github.com/raspberrypi/rpicam-apps/commit/0ca9f41fea587458b5b447c2b079328056452252 but I'll leave that change to someone actually using this, I was just fixing the build issue found in world builds
* tweak FILES to package library symlink without …
=> libcamera-apps: fix build with libcamera-0.2.0

recipes-kernel/linux/files/default-cpu-governor.cfg, recipes-kernel/linux/linux-raspberrypi.inc
This cherry-picks 0a4a68d from master into Kirkstone branch
=> [Kirkstone] backport patch: linux-raspberrypi: stop setting powersave as the default CPU governor

conf/machine/include/rpi-base.inc
There is anoter hifiberry hat, for which there is currently no overlay added to the build, so let's add it:
hifiberry-dacplusadcpro.dtbo
=> rpi-base: Add missing hifiberry overlay

recipes-multimedia/rpidistro-ffmpeg/rpidistro-ffmpeg_4.3.4.bb
=> rpidistro-ffmpeg: Fix old override syntax

recipes-bsp/rpi-eeprom/rpi-eeprom_git.bb
This follows the current latest release of rpi-eeprom: https://github.com/raspberrypi/rpi-eeprom
Updated pr version and tested updating eeprom
changed the version and the checksum
=> rpi-eeprom_git: v.2024.01.05-2712 Update recipe to latest rpi-eeprom

dynamic-layers/meta-python/recipes-devtools/python/python3-sense-hat_2.2.0.bb
Starting OE core commit b566b1e32c7993d1ab7795562f648e52ce186a70, we no longer need PYTHON_PN for any abstraction of python2 vs python3.
=> python3-sense-hat: Drop PYTHON_PN

wic/sdimage-raspberrypi.wks
* current aarch64 kernel image alone is 24MB: 24M tmp-glibc/deploy/images/raspberrypi4-64/Image-raspberrypi4-64-1-6.1.77+git0+43d1723dbe_77fc1fbcb5-r0.1-20110405230000.bin and with rpi-bootfiles it takes around 46MB (e.g. this is from kirkstone raspberrypi4-64 build):
```
2.0K    boot.scr
2.0K    cmdline.txt
4.0K    fixup4cd.dat
4.0K    fixup_cd.dat
4.0K    uEnv.txt
6.0K    fixup4.dat
8.0K    fixup.dat
10K     fixup4db.dat
10K     fixup4x.dat
10K     fixup_db.dat
10K     fixup_x.dat
16K     uboot.env
36K     config.txt
52K     bcm2711-rpi-4-b.dtb
52K     bcm2711-rpi-400.dtb
52K     bcm2711-rpi-cm4.dtb
52K     bootcode.bin
126K    overlays
558K    kernel8.img
786K    start4cd.elf
786K    start_cd.elf
2.2M    start4.elf
2.9M    start.elf
2.9M    start4x.elf
3.6M    start4db.elf
3.6M …
```
=> sdimage-raspberrypi.wks: increase /boot minimal size from 20 to 100

conf/machine/include/rpi-base.inc
Added missing support for HiFiBerry AMP100, AMP3, AMP4 Pro, DAC+ ADC Pro, DAC+ DSP, DAC+ HD, Digi Pro.
Add right lines to rpi-base.inc. Changes were tested and works fine with the branch.
Connected also with issue #1168
=> rpi-base: Added missing HiFiBerry

recipes-graphics/userland/files/0025-CMakeLists.txt-.pc-respect-CMAKE_INSTALL_LIBDIR.patch, recipes-graphics/userland/userland_git.bb
Be aware that whole userland repo is marked as ancient and deprecated: https://github.com/raspberrypi/userland/commit/96a7334ae9d5fc9db7ac92e59852377df63f1848 and explicitly says:
"If you are using code from here you should rethink your solution."
But even if your build is using vc4graphics in MACHINE_FEATURES to avoid most of userland, this issue with multilib was preventing do_install:append to actually remove those libraries provided by lib32-mesa when building lib32-userland (e.g. to provide virtual/libomxil or as dependency of raspidmx or runtime dependency of omxplayer).
=> userland: fix installed-vs-shipped in multilib builds

conf/layer.conf, conf/machine/raspberrypi5.conf, recipes-bsp/u-boot/u-boot_%.bbappend
1. Re-enable `u-boot` for `raspberrypi5`.
2. Add the `meta-lts-mixins` `scarthgap/u-boot` layer to LAYERRECOMMENDS (so that, for instance, [layerindex](https://layers.openembedded.org) can know about the recommendation).
3. Update the `KERNEL_IMAGETYPE_UBOOT` to be in line with `raspberypi4-64` so that it is functional.
Create a `meta-lts-mixins` `scarthgap/u-boot` branch so we can have newer u-boot than what is released in openembedded-core.
Known issues: For the author at least, a debug UART cable must be attached to the `UART` port between `HDMI0` and `HDMI`. We know the `u-boot` support in `v2024.04` was flagged as **initial** so we should not expect everything to be completely functional yet (usb, ethernet).
This is the same content as the mailing …
=> scarthgap/raspberrypi5 u-boot

recipes-kernel/linux/linux-raspberrypi_6.1.bb
This is needed for "iw reg" to work correctly with updated wireless-reg which was backported to kirkstone in:
https://git.openembedded.org/openembedded-core/commit/?h=kirkstone&id=11c9c6eec5ff45cd1fd4858bc28f38693c5d0fde
The necessary changes are included in 6.1.74, but bump to 6.1.77 to keep 6.1 revision in sync for kirkstone, mickledore, nanbield, master branches.
```
work-shared/raspberrypi4-64/kernel-source $ git log --oneline f364e0eb8f973e1aa24a3c451d18e84247a8efcd..1cdbd99f402b76c61632d09a49b20ce90af0cc72 | grep cfg80211                                     
dd9465b10880 wifi: cfg80211: lock wiphy mutex for rfkill poll …
```
=> [mickledore] linux-raspberrypi_6.1.bb: Upgrade to 6.1.77

recipes-bsp/bootfiles/rpi-cmdline.bb
Added `net.ifnames=0` kernel parameter into `CMDLINE`.
If we boot the kernel this way, the network interfaces will not be renamed. Otherwise it will be renamed.
Without parameter:
root@raspberrypi3-64:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
inet 127.0.0.1/8 scope host lo
valid_lft forever preferred_lft forever
inet6 ::1/128 scope host noprefixroute
valid_lft forever preferred_lft forever
2: enu1u1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel qlen 1000
link/ether b8:27:eb:d9:fd:59 brd ff:ff:ff:ff:ff:ff
3: wlxb827eb8ca80c: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
link/ether b8:27:eb:8c:a8:0c brd ff:ff:ff:ff:ff:ff
root@raspberrypi3-64:~# journalctl | grep wlan
Feb 27 17:26:08 …
=> rpi-cmdline: Fix being renamed of network interfaces

recipes-bsp/gpio-shutdown/gpio-shutdown.bb, recipes-bsp/u-boot/u-boot_%.bbappend, recipes-core/psplash/psplash_%.bbappend, recipes-core/udev/udev-rules-rpi.bb, recipes-core/udev/udev-rules-udisks-rpi_1.0.bb, recipes-graphics/vc-graphics/vc-graphics.inc, recipes-graphics/xorg-xserver/xserver-xf86-config_%.bbappend
UNPACKDIR is new contruct for do_unpack things in latest master we should be using that instead of WORKDIR for referencing those files
=> recipes: Switch to using UNPACKDIR instead of WORKDIR

recipes-kernel/linux/linux-raspberrypi_6.1.bb
This is needed for "iw reg" to work correctly with updated wireless-reg which was backported to kirkstone in:
https://git.openembedded.org/openembedded-core/commit/?h=kirkstone&id=11c9c6eec5ff45cd1fd4858bc28f38693c5d0fde
The necessary changes are included in 6.1.74, but bump to 6.1.77 to keep 6.1 revision in sync for kirkstone, mickledore, nanbield, master branches.
```
work-shared/raspberrypi4-64/kernel-source $ git log --oneline f364e0eb8f973e1aa24a3c451d18e84247a8efcd..1cdbd99f402b76c61632d09a49b20ce90af0cc72 | grep cfg80211                                     
dd9465b10880 wifi: cfg80211: lock wiphy mutex for rfkill poll …
```
=> [nanbield] linux-raspberrypi_6.1.bb: Upgrade to 6.1.77

conf/layer.conf, recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr.bb
* see: https://lists.openembedded.org/g/openembedded-architecture/message/2007
* fixes:
sed: can't read TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/rpi-u-boot-scr/1.0/boot.cmd.in: No such file or directory
=> [styhead] rpi-u-boot-scr: use UNPACKDIR

recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
Firmware links for model Zero 2 W were missing.
This patch sets the necessary links for brcmfmac firmware. Without the links, the firmware cannot be loaded without causing boot messages like: brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43430b0-sdio.raspberrypi,model-zero-2-w.bin failed with error -2
Fixes agherzan/meta-raspberrypi#1324
=> linux-firmware-rpidistro: Fix wireless on model Zero 2 W

recipes-bsp/u-boot/u-boot/0001-bootstd-Scan-all-bootdevs-in-a-boot_targets-entry.patch, recipes-bsp/u-boot/u-boot_2023.10.bbappend
* fixes: https://github.com/agherzan/meta-raspberrypi/issues/1338
* apply it in version specific u-boot_2023.10.bbappend so that if someone already uses newer version backported to nanbield it won't cause do_patch failure
* instead of:
```
U-Boot 2023.10 (Oct 02 2023 - 14:39:59 +0000)
DRAM:  948 MiB (effective 3.9 GiB) RPI 4 Model B (0xc03111) Core:  212 devices, 16 uclasses, devicetree: board
MMC:   mmcnr@7e300000: 1, mmc@7e340000: 0
Loading Environment from FAT... OK
In:    serial,usbkbd
Out:   serial,vidconsole
Err:   serial,vidconsole
Net:   eth0: ethernet@7d580000
PCIe BRCM: link up, 5.0 Gbps x1 (SSC)
starting USB...
Bus xhci_pci: Register 5000420 NbrPorts 5
Starting the controller
USB XHCI 1.00
scanning bus xhci_pci for devices... 2 USB Device(s) found
scanning usb for storage …
```
=> u-boot: backport one commit from v2024.01 to fix booting from uSD

kas-poky-rpi.yml
Fixed the warning from kas:
WARNING  - Using deprecated refspec for repository "poky". You should migrate to commit/tag/branch.
WARNING  - Using deprecated refspec for repository "meta-openembedded". You should migrate to commit/tag/branch.
WARNING  - Using deprecated refspec for repository "meta-qt5". You should migrate to commit/tag/branch.
=> kas: updated the refspec syntax of the kas file

README.md
in commit 01b162388e38eb7f7bdd77e80e20454672f993f9 with commit message:
rpi-base: Drop old dtbo names
pi3-disable-bt is renamed to disable-bt and pi3-miniuart-bt is renamed
to miniuart-bt in 2014, now with 5.4 these are not recognised anymore
and miniuart-bt and disable-bt are already part of RPI_KERNEL_DEVICETREE_OVERLAYS
=> README.md: pi3-disable-bt is renamed to disable-bt in kas example

recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr.bb
This adapts to the oe-core rework to enforce a separate directory for unpacking local sources (UNPACKDIR) instead of directly using WORKDIR.
Follows the preliminary guideline from:
https://lists.openembedded.org/g/openembedded-architecture/message/2007
Fixed issues with the S variable in newer Yocto and OpenEmbedded versions.
By following the guideline:
https://lists.openembedded.org/g/openembedded-architecture/message/2007
=> rpi-u-boot-scr: WORKDIR -> UNPACKDIR transition

conf/machine/include/rpi-base.inc
The overlay to disable Bluetooth is different for Raspberry Pi 5.
To disable the Bluetooth on a Raspberry Pi 5 a new device tree overlay is added to the /boot/overlays directory.
fixes #1346
=> rpi-base.inc: added the disable-bt-pi5 device tree overlay

recipes-core/udev/udev-rules-rpi.bb, recipes-core/udev/udev-rules-rpi/fb.rules
When using psplash in combination with systemd the splash screen is not shown. The dependency to sys-devices-platform-gpu-graphics-fb0.device will terminate psplash-start.service because systemd is not aware of the framebuffer device node.
See https://lists.yoctoproject.org/g/yocto/topic/91286438#57156
Adding a udev rule to notify systemd
=> psplash: udev rule to notify systemd of available framebuffers

conf/machine/include/rpi-default-providers.inc, docs/extra-build-config.md
Switch to defaulting to OE core ffmpeg &
meta-openembedded vlc.
**- Reason**
Upgrades to newer rpi-distro VLC version
in an OE environment have proven to be
tedious due to all the PI foundation patches.
Some patches aren't fully pushed into github
and require updates to build.
Maintaining patches have also proven to be unstable.
Default to stable builds of both so that peoples
builds aren't broken.
If rpi-distro version of ffmpeg & vlc wanted
users may switch by setting PREFFERED_PROVIDER.
@kraj @agherzan .
What do you guys think?
=> update vlc,ffmpeg PREFERRED_PROVIDER

conf/machine/include/rpi-base.inc
For Raspberry PI 5 we need a different device tree overlay to disable WiFi, so we need to explicitly enable it & install to `/boot/overlays`.
Added an appropriate dtbo to `RPI_KERNEL_DEVICETREE_OVERLAYS`.
=> rpi-base.inc: add the disable-wifi-pi5 overlay

conf/machine/include/rpi-base.inc
I think as we add by default the overlays `disable-bt `and `miniuart-bt ` to `RPI_KERNEL_DEVICETREE_OVERLAYS` we also need to add the overlays to enable the uart peripherals.
Indeed if we want to use the uart0 peripheral on a Raspberry PI4 with the PL011 with need to enable the following overlays:
```
dtoverlay=disable-bt
dtoverlay=uart0
```
Add all the uart dts overlays to `RPI_KERNEL_DEVICETREE_OVERLAYS`
=> rpi-base: build uart dts overlays by default

recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
The upgrade was necessary to get WLAN running on a CM4 (under scarthgap). Otherwise I continuously got the following kernel messages when trying to connect:
[   31.907395] brcmfmac: brcmf_set_channel: set chanspec 0xd022 fail, reason -52
[   32.023434] brcmfmac: brcmf_set_channel: set chanspec 0xd026 fail, reason -52
[   32.135403] brcmfmac: brcmf_set_channel: set chanspec 0xd02a fail, reason -52
[   32.247392] brcmfmac: brcmf_set_channel: set chanspec 0xd02e fail, reason -52
[   33.919395] brcmfmac: brcmf_set_channel: set chanspec 0xd090 fail, reason -52
[   33.926940] brcmfmac: brcmf_set_channel: set chanspec 0xd095 fail, reason -52
[   33.935151] brcmfmac: brcmf_set_channel: set chanspec 0xd099 fail, reason -52
[   33.942691] brcmfmac: brcmf_set_channel: set chanspec 0xd09d fail, …
=> linux-firmware-rpidistro: Upgrade to bookworm/20230625-2+rpt3

conf/layer.conf
Remove layer dependency from meta-lts-mixins 'scarthgap/u-boot' because now the BSP supports styhead which brings U-Boot 2024.07.
Removed layer dependency from meta-lts-mixins 'scarthgap/u-boot'. Historically, this dependency was added temporary to provide U-Boot 2024.04 instead of 2024.01 because of Raspberry Pi 5.
Modified `conf/layer.conf`
=> conf/layer.conf: Remove meta-lts-mixins

conf/layer.conf
The following line doubles BBFILES for all layers in BBFILE_COLLECTIONS: BBFILES += "${@' '.join('${LAYERDIR}/dynamic-layers/%s/recipes*/*/*.bb' % layer \
for layer in BBFILE_COLLECTIONS.split())}"
And most of them are invalid, use BBFILES_DYNAMIC is the correct solution.
=> conf/layer.conf: Remove duplicated BBFILES

recipes-multimedia/picamera-libs/picamera-libs.bb
Apparently the recipe for python3 picamera is installing some libraries from /opt/vc/lib that are not necessary to the picamera module. The gles2 library, in particular, overwrites a symlink to another version of the gles2 library. The result is that two different gles2 libs are placed in /usr/lib.
This commit removes a few unneeded libraries, leaving libmmal and its dependencies, that are instead required.
=> picamera-libs: removed unused libraries from python3-picamera

kas-poky-rpi.yml
* Added, but in comment, the synaptics-killswitch license.  Because it's easier to have in in the KAS file.
* The 'debug-tweaks' image_feature is removed in Yocto.
I replaced it with was under it.  But this is (and was) insecure.
**But I would be in favor of having this replaced by a more secure settings**.
It could be in comment as a warning to the user.
br
=> Some Kas stuff

.readthedocs.yaml
Deprecation of projects using Sphinx or MkDocs without an explicit configuration file:
https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
=> docs: Fix ReadTheDocs sphinx.configuration requirement

conf/machine/include/rpi-base.inc, conf/machine/raspberrypi-armv8.conf, conf/machine/raspberrypi5.conf
Fixes #1394 
This adds the required devicetree and overlays to the raspberrypi5.conf file to allow booting the RPi CM5 without a kernel panic.
Thanks @gokamura for finding the fix.
U-Boot still doesn't work in my testing, waiting to get the uart headers to see if there is some output there.
=> Fix boottime kernel panic on RPi CM5

dynamic-layers/multimedia-layer/recipes-multimedia/libcamera/libcamera_%.bbappend
Building libcamera from the latest meta-oe fails with QA check error:
```
ERROR: libcamera-1_0.4.0-r0 do_package_qa: QA Issue: File /usr/lib/libcamera.so.0.4.0 in package libcamera contains reference to TMPDIR [buildpaths]
ERROR: libcamera-1_0.4.0-r0 do_package_qa: QA Issue: File /usr/lib/libcamera-base.so.0.4.0 in package libcamera contains reference to TMPDIR [buildpaths]
ERROR: libcamera-1_0.4.0-r0 do_package_qa: QA Issue: File /usr/lib/libcamera/ipa_rpi_vc4.so in package libcamera contains reference to TMPDIR [buildpaths]
ERROR: libcamera-1_0.4.0-r0 do_package_qa: QA Issue: File /usr/libexec/libcamera/raspberrypi_ipa_proxy in package libcamera contains reference to TMPDIR [buildpaths]
ERROR: libcamera-1_0.4.0-r0 do_package_qa: QA Issue: File /usr/libexec/libcamera/v4l2-compat.so in …
```
=> libcamera: fix c++ flags and failed buildpaths QA check

recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
Switches the Raspberry Pi 5 to use the standard cyfman43455-sdio firmware by default. The minimal firmware on this device is unable to connect to a WiFi access point.
This also matches the behavior of Raspberry Pi OS, which defaults to the standard firmware
=> linux-firmware-rpidistro: Fix WiFi on Raspberry Pi 5

conf/machine/include/rpi-base.inc
=> [scarthgap] Backport rpi-base: build uart dts overlays by default

conf/machine/raspberrypi5.conf
fix raspberrypi5 boot up
solve https://github.com/agherzan/meta-raspberrypi/issues/1410
=> raspberrypi5: add bcm2712d0 overlay required for booting up correctly

recipes-graphics/mesa/mesa.bbappend
kmsro is no longer valid gallium-drivers, the PACKAGECONFIG will be removed by: https://lists.openembedded.org/g/openembedded-core/message/214763
we need to remove it here as well.
kmsro was removed in:
https://gitlab.freedesktop.org/mesa/mesa/-/commit/89863a050bea429d9574a307bc28953bb60accaf
This PR should be applied after branching for walnascar as mesa-25 is only in master for whinlatter.
=> [whinlatter] mesa: drop kmsro PACKAGECONFIG

recipes-bsp/armstubs/armstubs.bb, recipes-bsp/bootfiles/rpi-config_git.bb
With:
https://lists.openembedded.org/g/bitbake-devel/message/17508 there are WARNINGs like:
```
WARNING: meta-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bb: meta-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bb:21 has a lack of whitespace around the assignment: 'PITFT="${@bb.utils.contains("MACHINE_FEATURES", "pitft", "1", "0", d)}"'
WARNING: meta-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bb: meta-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bb:22 has a lack of whitespace around the assignment: 'PITFT22="${@bb.utils.contains("MACHINE_FEATURES", "pitft22", "1", "0", d)}"'
WARNING: meta-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bb: meta-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bb:23 has a lack of whitespace around the assignment: …
```
=> armstubs, rpi-config: add whitespace around assignments

README.md
How to set the MACHINE is described in 'Quick Start', but was missing in 'Quick Start with kas'
=> README.md: added how to set the machine when using Kas

recipes-graphics/mesa/mesa.bbappend
- remove DRIDRIVERS variable
Both are not available in current mesa recipe
This fixes:
ERROR: mesa-2_25.0.5-r0 do_recipe_qa: QA Issue: mesa: invalid PACKAGECONFIG(s): dri3 [invalid-packageconfig] ERROR: mesa-2_25.0.5-r0 do_recipe_qa: Fatal QA errors were found, failing task.
=> mesa: drop dri3 PACKAGECONFIG

conf/machine/include/rpi-default-versions.inc, recipes-bsp/bootfiles/rpi-bootfiles.bb, recipes-kernel/linux/linux-raspberrypi_6.12.bb
This commit updates linux-raspberrypi 6.12.2 -> 6.12.22 and make it the default kernel as pointed out in:
https://github.com/agherzan/meta-raspberrypi/pull/1406#issuecomment-2812110690
=> linux-raspberrypi: update 6.12 recipe

conf/machine/include/rpi-base.inc
Add vc4-kms-dsi-ili9881-7inch.dtbo for the Raspberry Pi Touch Display 2 to RPI_KERNEL_DEVICETREE_OVERLAYS.
This work was sponsored by GOVCERT.LU.
Enabled support for Raspberry Pi Touch Display 2
Added `vc4-kms-dsi-ili9881-7inch.dtbo` to `RPI_KERNEL_DEVICETREE_OVERLAYS`.
To load the dtbo by default at the following line to your build setup, for example in `local.conf`:
```
RPI_EXTRA_CONFIG:append = " \
dtoverlay=vc4-kms-dsi-ili9881-7inch \
"
```
By default Raspberry Pi Touch Display 2 works in portrait mode. To rotate it in landscape mode for Weston (from `core-image-weston`), Add the following configuration to `weston.ini`:
```
[output]
name=DSI-2
mode=720x1280@60
transform=rotate-90 
```
Please note that in this example Raspberry Pi Touch Display 2 has …
=> rpi-base.inc: vc4-kms-dsi-ili9881-7inch.dtbo

recipes-devtools/raspi-utils/raspi-utils_git.bb
The `raspi-utils` package that builds tools from the https://github.com/raspberrypi/utils repository neglected to include all of the utilities provided therein. I would like to include those missing utilities, so I added them to the recipe.
The `raspi-utils` recipe originally only built the `dtmerge` and `pinctrl` utilities. I've extended the recipe to include the other build targets which are:
* eeptools
* otpset
* overlaycheck
* ovmerge
* raspinfo
* vcgencmd
* vclog
* vcmailbox
I extended the `OECMAKE_TARGET_COMPILE` and `OECMAKE_TARGET_INSTALL` variables to include all the targets available in the upstream repository. The original variables become:
```shell
OECMAKE_TARGET_COMPILE = "\
dtmerge/all \
eeptools/all \
otpset/all \
overlaycheck/all \ …
```
=> raspi-utils: Add missing utilities like vcgencmd

conf/machine/include/rpi-base.inc
Add vc4-kms-dsi-ili9881-7inch.dtbo for the Raspberry Pi Touch Display 2 to RPI_KERNEL_DEVICETREE_OVERLAYS.
This work was sponsored by GOVCERT.LU.
Enabled support for Raspberry Pi Touch Display 2
Added `vc4-kms-dsi-ili9881-7inch.dtbo` to `RPI_KERNEL_DEVICETREE_OVERLAYS`.
To load the dtbo by default at the following line to your build setup, for example in `local.conf`:
```
RPI_EXTRA_CONFIG:append = " \
dtoverlay=vc4-kms-dsi-ili9881-7inch \
"
```
By default Raspberry Pi Touch Display 2 works in portrait mode. To rotate it in landscape mode for Weston (from `core-image-weston`), Add the following configuration to `weston.ini`:
```
[output]
name=DSI-2
mode=720x1280@60
transform=rotate-90 
```
Please note that in this example Raspberry Pi Touch Display 2 has …
=> [scarthgap] rpi-base.inc: vc4-kms-dsi-ili9881-7inch.dtbo

conf/machine/include/rpi-default-versions.inc, recipes-bsp/bootfiles/rpi-bootfiles.bb, recipes-kernel/linux/linux-raspberrypi-v7_6.12.bb, recipes-kernel/linux/linux-raspberrypi_6.12.bb
Adds support for the Raspberry Pi fork of the Linux kernel version 6.12 as well as the required firmware.
Cherry-picked patches from branch master to scarthgap and tested on Raspberry Pi 5. This is related to https://github.com/agherzan/meta-raspberrypi/pull/1462
This pull request replaces #1479.
On a side note, during the test I noticed:
```
root@raspberrypi5:~# dmesg | grep error
[    5.170687] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43455-sdio.raspberrypi,5-model-b.bin failed with error -2
[    5.678945] rp1-pio 1f00178000.pio: probe with driver rp1-pio failed with error -2
```
Based on my experience this is related to https://github.com/agherzan/meta-raspberrypi/pull/1408 so after merging PR #1408 in master we should also port it …
=> [scarthgap] Raspberry Pi Linux kernel 6.12

.github/actions/docker-build/action.yml, .github/workflows/docker-images/README.md
* --no-cache is needed to actually call apt update instead of using it from docker cache and then failing to fetch pruned packages as shown: https://github.com/agherzan/meta-raspberrypi/actions/runs/16327036376/job/46119768952?pr=1491
=> [scarthgap] docker-build: use --no-cache

recipes-devtools/raspi-utils/raspi-utils_git.bb
I added the `raspi-utils` recipe to the `scarthgap` branch.
I simply copied the recipe from `master`, additionally defining the `S` variable in order to build correctly with Scarthgap.
Tested on `MACHINE=raspberrypi4-64`.  Builds without issue, and `vcmailbox` works:
```
root@raspberrypi4-64:~# vcmailbox 0x00010004 8 8 0 0
0x00000020 0x80000000 0x00010004 0x00000008 0x80000008 0xba160283 0x10000000 0x00000000
```
**- Why I did it**
I need access to the `vcmailbox` utility.  This is included in the `master` branch's `raspi-utils` recipe, but that recipe is not included in the `scarthgap` branch
=> add raspi-utils recipe to scarthgap branch

conf/machine/include/rpi-base.inc, docs/extra-build-config.md, recipes-bsp/bootfiles/rpi-config_git.bb
Hey,
I needed support of the [seeed-can-fd-hat-v2 Can Shield](https://wiki.seeedstudio.com/2-Channel-CAN-BUS-FD-Shield-for-Raspberry-Pi/) so I added it to the layer. 
I tested the changes on my rpi4.
=> support-for-seeed-can-fd-hat-v2

conf/machine/raspberrypi3-64.conf, conf/machine/raspberrypi4-64.conf
SOCs used in rpi3 and rpi4 do not have AES crypto HW engine denote it by using more appropriate default tune, this ensures that it enforces +nocrypto into -mtune regardless of gcc or clang compiler.
=> raspberrypi3-64,raspberrypi4-64: Use nocrypto default tunes

dynamic-layers/multimedia-layer/recipes-multimedia/libcamera-apps/libcamera-apps_git.bb
Package rpicam_app.so.1.4.2 library for the default package to fix the following error.
ERROR: libcamera-apps-1.4.2+git-r0 do_package: QA Issue: libcamera-apps: Files/directories were installed but not shipped in any package:
/usr/lib/rpicam_app.so.1.4.2
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install. libcamera-apps: 1 installed and not shipped files. [installed-vs-shipped] ERROR: libcamera-apps-1.4.2+git-r0 do_package: Fatal QA errors were found, failing task. ERROR: Logfile of failure stored in: /home/build-2/tmp/work/cortexa53-poky-linux/libcamera-apps/1.4.2+git/temp/log.do_package.1110484 ERROR: Task (/home/meta-raspberrypi/dynamic-layers/multimedia-layer/recipes-multimedia/libcamera-apps/l …
=> libcamera-apps: Fix library packaging issues for rpicam_app.so.1.4.2

recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro/0002-Default-all-RPi-43455-boards-to-standard-variant.patch, recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb
Fix an error message generated when creating an image with brcmfmac enabled.
As #1396 describes, the brcmfmac driver generates an error message during boot, which can be seen by inspecting the log of the device.
This error happens because several files in linux-firmware-rpidistro links to non-existing files.
By updating the link of these files to the valid files in the target, this error message is fixed.
Create a patch file for the linux-firmware-rpidistro recipe, that changes the links of different rpi board firmware files from linking to non-existing files, to link to the file which exists in the system.
A similar change was already implemented for the base file - this PR do the same fix for all the rest of the RPi files, so no error message will be …
=> linux-firmware-rpidistro: Fix wireless error message on RPi

conf/machine/raspberrypi2.conf
Add the relevant QB_ variables sufficient to get the QEMU raspi2b model running with runqemu.
These changes require 
https://lists.openembedded.org/g/openembedded-core/message/222548
https://lists.openembedded.org/g/openembedded-core/message/222549
=> raspberrypi2.conf: add QB_ variables for runqemu

.github/workflows/yocto-builds.yml, conf/machine/raspberrypi-armv8.conf, conf/machine/raspberrypi2-64.conf, docs/layer-contents.md
This machine configuration is for the Raspberry Pi 2B V1.2 (64-bit).
Note: Raspberry Pi 2 Model B V1.2[1] switched from BCM2836[2] (V1.0, V1.1) to BCM2837[3] that is 64-bit CPU used in Raspberry Pi 3 Model B.
BCM2836[2]
The Broadcom chip used in the Raspberry Pi 2 Model B. The
underlying architecture in BCM2836 is identical to BCM2835. The
only significant difference is the removal of the ARM1176JZF-S
processor and replacement with a quad-core Cortex-A7 cluster.
BCM2837[3]
This is the Broadcom chip used in the Raspberry Pi 3 Model B,
later models of the Raspberry Pi 2 Model B, and the Raspberry Pi
Compute Module 3. The underlying architecture of the BCM2837 is
identical to the BCM2836. The only significant difference is the
replacement of the ARMv7 quad core cluster with a quad-core ARM …
=> raspberrypi2-64.conf: add machine for Raspberry Pi 2B V1.2 (64-bit)
